### ISSUE TITLE
Google Voice/Hangouts: only received messages backed up

### ISSUE THREAD

**Issue by rogermhsu** [jberkel/sms-backup-plus#516] opened 2015-01-03 22:00 UTC
I've been a long-time user of this app and just kind of trusted it to do its job. Recently, however, I realized that only messages I received are being backed up, while sent messages are not (note that there is a similar bug that is the exact opposite in which only sent messages are backed up and received messages are not). In searching through my SMS emails, it looks like this problem started occurring between 11/30/2013 and 12/04/2013 (yes, it took a long time for me to realize this was occurring).

Info:
- SMS Backup+ 1.5.7 (but problem started occurring in 12/2013)
- Android 5.0.1 (but problem started occurring in 12/2013)
- Nexus 5 as of 8/2014, but the problem started occurring prior to that with my Samsung Galaxy S3.
- T-Mobile as of 8/2014, but the problem started occurring prior to that while I was with Ting, an mobile service that uses the Sprint network.
- My SMS number is with Google Voice in case that might make any difference.

Hopefully this issue can be fixed soon!

**Comment by DPLaC** [comment] 2015-09-14 00:17
For me, no messages sent via Google Voice (I use Hangouts for an app) get backed up — neither sent nor received.

**Comment by WirelessJoe123** [comment] 2016-10-04 18:40
Hello,

I am not using Google Voice, and only my received messages are being backed up to gmail. This appears to have been the case since I first installed September 19, 2016.   
SMS backup 1.5.10
Samsung -SM-G890A
Android 6.0.1
AT&T

**Comment by DrTwister** [comment] 2016-11-12 15:52
I can confirm this. As a long time user, this has only began for me in the last week or 2. At least I've only just now noticed it today. It will back up received messages, and MMS messages that are received and sent, but not SMS messages that are sent.

This was never previously an issue for me.  Nothing has changed.

Seems like similar details as wirelessJoe123

**Comment by DrTwister** [comment] 2016-11-12 18:46
My issue has to do with Advanced Messaging.  Messages that are sent as Advanced Messages do not get recognized or backed up. I have validated this multiple times now, and I have used other SMS backup apps that also are not able to recognized messages that were sent with Advanced Messaging turned ON.  Turn it off, and SMS Backup will backup sent and received messages 

SMS backup 1.5.11
Galaxy S7 Edge
Android 6.0.1
AT&T

**Comment by icufoundme** [comment] 2016-12-08 06:24
I thought I was having the same issue as @rogermhsu; For my Google Voice number, only inbound SMS messages are backing up to my gmail 'SMS' folder. 
All SMS messages to/from my Verizon carrier number are being backed up perfectly.

BUT... After some troubleshooting, I actually discovered that SMS Backup+ is not backing up ANY  messages to/from my GV number. 

The 'received' SMS messages for my gvoice number that are showing up in gmail were actually sent there by google voice backup settings, not SMS Backup+. In my "SMS" folder in gmail, SMS Backup+ emails have subject "SMS with", and Google Voice emails have the subject "SMS from". 
 
The setting is in [Google Voice](https://www.google.com/voice/b/0#voicemailsettings) , Settings -  Voicemail and Text - enable Text Forwarding. 
This is why I am seeing the GV received texts as emails in my SMS folder in gmail. (I haven't figured out  why google voice does not back up the sent messages to email. They show up fine in the web interface for gvoice.)

You can 'fix' this by enabling this in GV: settings - Phones - Mobile - receive text messages on this phone. 
Which should mix both numbers in your default messaging app, and use your carrier number, boo. But it should allow all messages to be backed up in SMS Backup+ elegant style. 
Disable the previously mentioned "Text Forwarding" if you don't want duplicates.

I'm still dreaming of a universal messaging app that will let me use both my numbers separately, see all communications by contact, and backup neatly to email. It would also be nice if SMS backup+ could backup Hangouts and Google Voice messages that are not processed by the carrier. Too bad Google doesn't have an API for hangouts.

**Comment by ferdilverdil** [comment] 2017-02-15 16:03
I reported the same issue to J Berkel over a year ago. Never received a reply. Still have the same issue.
Only received texts are backed-up, not sent texts.  Also there seems to be an issue with the order the texts are backed-up. Things are out of order.

Anyone having any luck getting a fix for this???

**Comment by Master-BK** [comment] 2017-02-15 16:22
From what I can tell... The messages that don't back up for me are called "advanced messages", which are not considered SMS messages. Which is why the program won't pull them. I can't speak for other phones, other than my own. I have a Galaxy s7 edge. A temporary fix is to turn off advanced messaging. Go into the default text messaging app, open the settings menu that is located inside the message app (I have to click the "more"  button and then "settings"  while inside the text app). Then while inside the settings app, click on advanced messaging. And then switch it all off.  This only applies to future texts that sre sent, not the current text that are on the phone. It won't convert existing messages to SMS. On my phone, you can actually hold your finger  down on any text message to bring up options about the specific text. When you, you can click on "message details".  In the next menu, it shows what type of text message it is for the "type"  of message. It says either "Text Message",  "Advanced Message",  or "MMS".  This app only pulls messages that are Text (SMS)  or MMS. Hope this helps a little.

**Comment by ferdilverdil** [comment] 2017-02-15 16:26
I'll give it a shot, thanks. Problem is, it just suddenly stopped backing up correctly one night. Nothing changed on my phone settings. 
If I can restore all of the backed-up texts to my phone is there any other app you know of that will transfer everything on my phone, (assuming your fix helps with future texts) keeping them in conversational order?

**Comment by Master-BK** [comment] 2017-02-15 16:54
Honestly, I have only used the backup feature.  So any text I get, gets backed up to my Gmail.  I have never tried to take what was in my Gmail, and restore it on my phone with this app (can't verify it works).  I have however, used multiple apps to try and backup my texts.  All of them have the exact same result when trying to backup SMS and MMS vs an Advanced Message. (All of the apps never back up the advanced messages) I actually spent money on one of the apps though.  Here is the website http://emailtextmessages.info/ (it's on the Google play store, too).  I love how this app formats the text in my Gmail inbox in a nice readable format.  It was worth the 5 bucks to me.  It makes it easy to print these text out for court purposes (puts the texts in order, as well as an photos that were in the text).  This app won't restore from your Gmail back to your phone, though.  I don't think this really answers your question.  I am not sure I have the correct answer you are looking for.  Thanks.

**Comment by ferdilverdil** [comment] 2017-02-15 18:43
Thanks! Disabling Advanced Messages in the settings on my phone worked for backing up new sent and received texts. I just confirmed it.  I wish there was a way to back up advanced messages previously sent.  
I assume the email text messages link you sent me won't work for that as far as you know, right?

**Comment by Master-BK** [comment] 2017-02-15 20:39
As far as I know, it won't.  I want the same thing. I want to be able to back up advanced messaging messages. I have some important ones I need. That is partly the reason I started this app. I am interested in how this application reads SMS and mms messages. I am interested in trying to figure out how to modify this program in order to retrieve advanced messages. I have a feeling that there is not an api available yet, that allows you to programmaticlly retrieve advanced messages yet, other wise,  all the apps on the app store would have this functionality, by now.

**Comment by Master-BK** [comment] 2017-02-15 20:41
The way I am currently backing up advanced messaging is taking a screen shot of each text page and then sending to my email that way. Very time consuming. Was also thinking about making an app that did that, take pictures of a text thread for me and email them to myself.

**Comment by mrvitaminc** [comment] 2019-03-02 00:31
My problem was solved by the comment from Dr. Twister on November 12, 2016.  As soon as I set ADVANCED MESSAGES to OFF, my outgoing messages were backed up.  Mr.? Berkel suggested "Do you use a non-standard app like Google Voice/Hangouts or Signal to send messages? It could also be a device specific problem."  Nope, nope, and nope.  Much more common for a novice like me to get caught from a "harmless" messaging option, ADVANCED MESSAGES.

**Comment by SevnSins** [comment] 2019-12-20 21:46
disabling advanced messaging worked for me as well. :-)

**Comment by kurahaupo** [comment] 2019-12-25 12:57
@nikkopt As the lack of support for RCS is a known issue, are you sure you're seeing RCS messages backed up by SMS Backup+? Instead, perhaps, might it be backing up MMS; or might RCS be being backed up directly by your messaging app?

**Comment by kurahaupo** [comment] 2019-12-25 12:59
Does anyone still have this issue where it's _not_ connected to using RCS messaging (having "Advanced Messaging" enabled in your Messages app)?

**Comment by nikkopt** [comment] 2019-12-25 16:37
@kurahaupo i don't use RCS with my main contacts. Anyway, i messaged a guy who i know is using the google messages app (like me) and has RCS turned on (when the message you send isn't a RCS message, it will show "SMS" or "MMS" below the send arrow), and just to be sure, i also turned on airplane mode, to force the app to use wifi to send the messages. Then i used SMS backup+ to back them up and it was like last time, it creates a different conversation for the sender and receiver, but it backs them up. One thing to note: when the app is backing up the messages, it says "Backing up MMS", or something like that, so for the app those messages appear as MMS's, so you need to have the option to backup MMS's in the app turned on for it to work, at least for me.

**Comment by kurahaupo** [comment] 2020-04-26 07:14
Thanks @nikkopt 

BTW, there have been several updates to SMS Backup since this issue was raised; does this problem still exist in the most recent version (1.6β) of SMS Backup?

**Comment by kurahaupo** [comment] 2020-07-08 04:13
As it seems that the majority of issues reported here are actually RCS-related, I'm going to close this ticket.

@Master-BK to answer your query about "how", please see my follow-up in feature request #1027.

**Closed** 2020-07-08 04:13 UTC
Labels: AM+RCS, awaiting response, backup, v1.5.7
