### ISSUE TITLE
Restore marks restore time not previous sms time

### ISSUE THREAD

**Issue by antwonw** [jberkel/sms-backup-plus#94] opened 2010-12-12 13:55 UTC
Had to factory reset my phone. I wanted to restore my text messages from before. I restored and now all my txts list the date and time they were restored on my phone, not the time they were originally received before.

**Comment by jberkel** [comment] 2015-06-12 11:54
I tried this with Android 5.1 (emulator) and could not reproduce. Timestamps are correct there. Think it might be device specific. Closing.

**Closed by jberkel** 2015-06-12 11:54 UTC
