### ISSUE TITLE
Backup or Skip all messages PROBLEM - First but not First backup HELP Needed 

### ISSUE THREAD

**Issue by TheMattD** [jberkel/sms-backup-plus#886] opened 2018-04-21 17:15 UTC
Hello All, 
I recently switched phones from a Galaxy S5 with a broken charging port to another Galaxy S5. I have been using Backup+ to back up and restore messages for years so I do have a Gmail label set with my messages as SMS. 
To transfer data this time I used Samsung Smart Switch. Everything transferred over and my new GS5 is set, I hadn't backed up my SMS to Gmail in a few days so I went to do it today and it asked:
"FIRST BACKUP" 
"Backup or skip all messages currently stored  on this device?"
"Skip or Backup"

If I skip then it doesn't recognize ANY of my SMS currently on the phone as needing to be backed up. 
If I select "Backup" then it wants to backup ALL my SMS which I know 95% of them are already in Gmail... I am just trying to backup the last few days worth which should only be about 25 texts. 
So the app is recognizing none or ALL instead of just the 25 or so that are new in my phone and not yet backed up to Gmail.. 

Is there a way around this so I am not backing up loads of duplicates now? 

Before you report your issue, please search the issues page to see if it has already been reported. Also, if you'd like, you can try out the [beta version](https://github.com/jberkel/sms-backup-plus#beta).

### Expected behaviour
Backup only a few new messages from phone to SMS label in Gmail skipping messages that already exist from previous back ups in gmail

### Actual behaviour
If I select "skip" as in skip what's on the phone then it skips everything, but by selecting "Backup" it shows it wants to backup ALL my SMS instead of just what is new. 
### Steps to reproduce the behaviour
Download app, connect it to the gmail account, then select to backup, then select backup and it proceeds to backup ALL messages, even what is already in gmail. 

### Please specify the following:

* Android version
6.0.1

* Phone model / brand
Samsung Galaxy S5 from Verizon (SM-G900V) 

* SMS Backup+ version installed
1.5.11-beta17  

* Messaging app
Messages+ by Verizon

**Comment by Woi** [comment] 2018-04-22 20:11
Looks like a duplicate of #843

**Comment by jcrben** [comment] 2018-07-14 18:35
Check out https://github.com/jberkel/sms-backup-plus#how-do-i-restore-the-last-n-weeks--n-messages:
> If you have a lot of messages backed up (let's say over 5000) restoring can be very slow, especially if you're only interested in the most recent messages.
> A workaround is to use the Gmail web interface (or an IMAP email client) to move the bulk of the messages to another label in Gmail (e.g. SMSARCHIVED), and only keep a few hundred or so messages in the SMS label.

**Comment by kurahaupo** [comment] 2020-04-27 03:46
agreed, looks like a duplicate, and also no response, so closing issue

**Closed by kurahaupo** 2020-04-27 03:46 UTC
