### ISSUE TITLE
Error During Restore: IO Error

### ISSUE THREAD

**Issue by joshuatly** [jberkel/sms-backup-plus#675] opened 2016-09-06 13:45 UTC
Hi, Im having difficulties restoring sms to my phone. 
OnePlus One, CyanogenOS, 6.0.1, no root.

I have no problem backing SMS up. Please assist.
I ran logcat on PC and get the output below.

Let me know if there are any other information I can share to help fix this.

Thanks

```
09-06 21:39:25.577  3296  3296 I Auth    : [AuthDelegateWrapper] Service intent:
 Intent { cmp=com.google.android.gms/.auth.account.authenticator.DefaultAuthDele
gateService }.
09-06 21:39:25.578  3296  3296 I Auth    : [AuthDelegateWrapper] Service intent:
 Intent { cmp=com.google.android.gms/.auth.account.authenticator.DefaultAuthDele
gateService }.
09-06 21:39:25.580 11415 16740 I PlayCommon: [893] com.google.android.play.a.l.e
(789): No file ready to send
09-06 21:39:25.591  3296  8796 I GCoreUlr: Successfully inserted 1 locations
09-06 21:39:25.615 11415 11447 I PlayCommon: [810] com.google.android.play.a.l.a
(927): Connecting to server: https://play.googleapis.com/play/log?format=raw&pro
to_v2=true
09-06 21:39:25.623 11415 11447 W System  : ClassLoader referenced unknown path:
/system/framework/tcmclient.jar
09-06 21:39:25.633  3296 10186 I Places  : afoc.a:301: Unsuccessful place infere
nce - status code 20
09-06 21:39:26.202 11415 11447 I PlayCommon: [810] com.google.android.play.a.l.a
(1002): Successfully uploaded logs.
09-06 21:39:26.205 11415 11447 I PlayCommon: [810] com.google.android.play.a.l.e
(787): Preparing logs for uploading
09-06 21:39:26.208 11415 11447 I PlayCommon: [810] com.google.android.play.a.l.e
(789): No file ready to send
09-06 21:39:26.307  1715  3578 I PackageManager: Replacing preferred activity co
m.zegoggles.smssync/.compat.ComposeSmsActivity for user 0:
09-06 21:39:26.307  1715  3578 I PackageManager:   Action: "android.intent.actio
n.SENDTO"
09-06 21:39:26.307  1715  3578 I PackageManager:   Category: "android.intent.cat
egory.DEFAULT"
09-06 21:39:26.307  1715  3578 I PackageManager:   Scheme: "sms"
09-06 21:39:26.307  1715  3578 I PackageManager:   AutoVerify=false
09-06 21:39:26.311  1715  2801 I PackageManager: Replacing preferred activity co
m.zegoggles.smssync/.compat.ComposeSmsActivity for user 0:
09-06 21:39:26.311  1715  2801 I PackageManager:   Action: "android.intent.actio
n.SENDTO"
09-06 21:39:26.311  1715  2801 I PackageManager:   Category: "android.intent.cat
egory.DEFAULT"
09-06 21:39:26.311  1715  2801 I PackageManager:   Scheme: "smsto"
09-06 21:39:26.311  1715  2801 I PackageManager:   AutoVerify=false
09-06 21:39:26.313  1715  3249 I PackageManager: Replacing preferred activity co
m.zegoggles.smssync/.compat.ComposeSmsActivity for user 0:
09-06 21:39:26.314  1715  3249 I PackageManager:   Action: "android.intent.actio
n.SENDTO"
09-06 21:39:26.314  1715  3249 I PackageManager:   Category: "android.intent.cat
egory.DEFAULT"
09-06 21:39:26.314  1715  3249 I PackageManager:   Scheme: "mms"
09-06 21:39:26.314  1715  3249 I PackageManager:   AutoVerify=false
09-06 21:39:26.317  1715  1715 I PackageManager: Replacing preferred activity co
m.zegoggles.smssync/.compat.ComposeSmsActivity for user 0:
09-06 21:39:26.317  1715  1715 I PackageManager:   Action: "android.intent.actio
n.SENDTO"
09-06 21:39:26.317  1715  1715 I PackageManager:   Category: "android.intent.cat
egory.DEFAULT"
09-06 21:39:26.317  1715  1715 I PackageManager:   Scheme: "mmsto"
09-06 21:39:26.317  1715  1715 I PackageManager:   AutoVerify=false
09-06 21:39:26.318  1715  1715 I DefaultPermGrantPolicy: Granting permissions to
 default sms app for user:0
09-06 21:39:26.335 16426 16426 D SMSBackup+: onActivityResult(1,-1,null)
09-06 21:39:26.349 16426 16426 D SMSBackup+: onResume()
09-06 21:39:26.349  2787  2787 V PhoneStatusBar: setLightsOn(true)
09-06 21:39:26.365 12128 12141 D OpenGLRenderer: endAllStagingAnimators on 0x9a8
66200 (RippleDrawable) with handle 0x9b1bed70
09-06 21:39:26.411 16426 16426 W ContextImpl: Implicit intents with startService
 are not safe: Intent { act=com.android.vending.billing.InAppBillingService.BIND
 } android.content.ContextWrapper.bindService:610 com.github.jberkel.pay.me.IabH
elper.startSetup:152 com.zegoggles.smssync.activity.donation.DonationActivity.ch
eckUserHasDonated:244
09-06 21:39:26.417  1715  9223 W InputMethodManagerService: Window already focus
ed, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Pr
oxy@acfb24a attribute=null, token = android.os.BinderProxy@e58124f
09-06 21:39:26.429 16426 16758 D SMSBackup+: clearing cache in /data/user/0/com.
zegoggles.smssync/cache
09-06 21:39:26.434 16426 16426 D SMSBackup+: using new contacts API
09-06 21:39:26.451  1715  3578 D WifiService: acquireWifiLockLocked: WifiLock{SM
SBackup+ type=3 binder=android.os.BinderProxy@1fda5bb}
09-06 21:39:26.451  1715  2741 E native  : do suspend false
09-06 21:39:26.454 11415 12483 I Finsky  : [825] com.google.android.finsky.billi
ng.iab.r.a(5175): com.zegoggles.smssync: Account determined from installer data
- [rrHwknitXcfwTaZ5GAZ_OhOwekw]
09-06 21:39:26.456 11415 11426 I Finsky  : [793] com.google.android.finsky.billi
ng.iab.r.a(5175): com.zegoggles.smssync: Account determined from installer data
- [rrHwknitXcfwTaZ5GAZ_OhOwekw]
09-06 21:39:26.462 11415 11425 I Finsky  : [792] com.google.android.finsky.billi
ng.iab.r.a(5175): com.zegoggles.smssync: Account determined from installer data
- [rrHwknitXcfwTaZ5GAZ_OhOwekw]
09-06 21:39:26.465 11415 12483 I Finsky  : [825] com.google.android.finsky.billi
ng.iab.r.a(5175): com.zegoggles.smssync: Account determined from installer data
- [rrHwknitXcfwTaZ5GAZ_OhOwekw]
09-06 21:39:27.030 16426 16760 W k9      : Local key store has not been initiali
zed
09-06 21:39:30.629  1715  4734 D NetlinkSocketObserver: NeighborEvent{elapsedMs=
1474470, 192.168.88.1, [E48D8C4DADBC], RTM_NEWNEIGH, NUD_REACHABLE}
09-06 21:39:46.590  1715  4734 D NetlinkSocketObserver: NeighborEvent{elapsedMs=
1490430, 192.168.88.1, [E48D8C4DADBC], RTM_NEWNEIGH, NUD_STALE}
09-06 21:40:00.572  9457 16821 I System.out: send frame: Framedata{ optcode:TEXT
, fin:true, payloadlength:[pos:0, len:493], payload:[123, 34, 102, 114, 111, 109
, 34, 58, 34, 112, 104, 111, 110, 101, 34, 44, 34, 118, 101, 114, 34, 58, 34, 50
, 48, 49, 53, 57, 34, 44, 34, 100, 101, 118, 105, 99, 101, 105, 100, 34, 58, 34,
 34, 44, 34, 112, 116, 121, 112, 101, 34, 58, 34, 100, 101, 118, 105, 99, 101, 9
5, 101, 118, 101, 110, 116, 34, 44, 34, 98, 105, 100, 34, 58, 34, 49, 52, 55, 51
, 49, 54, 57, 50, 48, 48, 53, 54, 56, 34, 44, 34, 101, 116, 121, 112, 101, 34, 5
8, 34, 51, 34, 44, 34, 112, 107, 101, 121, 34, 58, 34, 34, 44, 34, 98, 111, 100,
 121, 34, 58, 34, 68, 52, 69, 52, 66, 67, 70, 70, 51, 67, 52, 57, 57, 51, 53, 57
, 69, 55, 66, 52, 50, 52, 51, 67, 50, 56, 54, 48, 67, 68, 49, 68, 66, 48, 65, 48
, 54, 70, 56, 55, 56, 67, 66, 51, 57, 56, 53, 57, 50, 56, 57, 49, 49, 49, 67, 67
, 54, 51, 48, 53, 66, 57, 67, 53, 65, 48, 57, 54, 56, 54, 48, 50, 52, 54, 52, 69
, 66, 65, 70, 68, 65, 55, 66, 50, 56, 70, 65, 65, 49, 53, 50, 70, 57, 49, 52, 56
, 57, 52, 67, 65, 67, 67, 57, 69, 66, 57, 68, 52, 68, 69, 52, 65, 56, 50, 54, 70
, 49, 67, 65, 66, 51, 65, 49, 68, 48, 56, 65, 56, 69, 52, 65, 67, 69, 67, 67, 49
, 50, 49, 70, 57, 52, 66, 70, 51, 50, 70, 69, 67, 55, 53, 48, 49, 49, 69, 55, 68
, 52, 54, 50, 66, 51, 65, 48, 48, 49, 66, 51, 48, 69, 49, 54, 65, 66, 55, 53, 48
, 68, 66, 67, 50, 54, 70, 48, 49, 48, 56, 53, 48, 50, 57, 52, 56, 49, 65, 56, 57
, 65, 49, 69, 50, 66, 66, 53, 52, 50, 56, 66, 49, 67, 67, 51, 56, 50, 69, 54, 55
, 68, 53, 50, 48, 66, 69, 70, 66, 69, 52, 68, 56, 54, 57, 69, 68, 49, 52, 69, 70
, 50, 49, 67, 49, 52, 54, 54, 56, 68, 70, 65, 65, 70, 48, 51, 51, 69, 51, 70, 54
, 69, 49, 65, 50, 55, 69, 67, 70, 53, 49, 54, 53, 49, 53, 54, 68, 53, 68, 50, 68
, 53, 56, 56, 54, 52, 66, 50, 57, 69, 49, 49, 56, 69, 69, 52, 65, 69, 49, 67, 50
, 67, 54, 65, 56, 56, 66, 66, 52, 65, 69, 67, 68, 53, 65, 57, 57, 53, 52, 53, 49
, 49, 57, 53, 68, 67, 67, 68, 56, 69, 53, 49, 54, 67, 55, 52, 57, 70, 55, 48, 51
, 50, 48, 68, 57, 69, 49, 48, 56, 70, 49, 55, 50, 50, 65, 53, 68, 55, 67, 70, 48
, 67, 65, 55, 70, 53, 67, 67, 50, 48, 54, 51, 54, 34, 125, 40, 93, 91, 41]}
09-06 21:40:00.573  9457 16821 I System.out: write(497): {锟絶锟絳"from":"phone
","ver":"20159","deviceid":"","ptype":"device_event","bid":"1473169200568","etyp
e":"3","pkey":"","body":"D4E4BCFF3C499359E7B4243C2860CD1DB0A06F878CB39859289111C
C6305B9C5A0968602464EBAFDA7B28FAA152F914894CACC9EB9D4DE4A826F1CAB3A1D08A8E4ACECC
121F94BF32FEC75011E7D462B3A001B30E16AB750DBC26F01085029481A89A1E2BB5428B1CC382E6
7D520BEFBE4D869ED14EF21C14668DFAAF033E3F6E1A27ECF5165156D5D2D58864B29E118EE4AE1C
2C6A88BB4AECD5A995451195DCCD8E516C749F70320D9E108F1722A5D7CF0CA7F5CC20636"}(][)}

锟斤拷锟斤拷Vk锟絵7 14605 I System.out: process(19): {锟斤拷nf蠁
09-06 21:40:23.285  9457 14605 I System.out: matched frame: Framedata{ optcode:T
EXT, fin:true, payloadlength:[pos:0, len:5], payload:[99, 104, 101, 99, 107]}
09-06 21:40:23.286  9457 14605 I System.out: matched frame: Framedata{ optcode:C
LOSING, fin:true, payloadlength:[pos:0, len:2], payload:[3, -17, -65, -67]}code:
 1001
09-06 21:40:23.288  9457 14605 I System.out: send frame: Framedata{ optcode:CLOS
ING, fin:true, payloadlength:[pos:0, len:2], payload:[3, -17, -65, -67]}code: 10
01
09-06 21:40:23.288  9457 14605 I System.out: write(4): {锟?锟絵
09-06 21:40:25.593  3296  4548 D LocationFilter: Forcing stable location. Origin
al location:Location[fused 3.203899,101.735894 acc=30 et=+25m29s408ms {Bundle[{w
ifiScan=[B@771eeb3, noGPSLocation=Location[fused 3.203899,101.735894 acc=30 et=+
23m15s670ms {Bundle[mParcelledData.dataSize=188]}], locationType=3}]}] because S
MD didn't trigger.
09-06 21:40:25.642  3296  8796 I GCoreUlr: Successfully inserted 1 locations
09-06 21:40:29.412  1715  4734 D NetlinkSocketObserver: NeighborEvent{elapsedMs=
1533253, 192.168.88.1, [E48D8C4DADBC], RTM_NEWNEIGH, NUD_PROBE}
09-06 21:40:31.534 16426 16760 E k9      : IOException for com.zegoggles.smssync
.mail.BackupStoreConfig@5646414:SMS/AsyncTask #4/conn83497510
09-06 21:40:31.534 16426 16760 E k9      : java.net.SocketTimeoutException: Read
 timed out
09-06 21:40:31.534 16426 16760 E k9      :      at com.android.org.conscrypt.Nat
iveCrypto.SSL_read(Native Method)
09-06 21:40:31.534 16426 16760 E k9      :      at com.android.org.conscrypt.Ope
nSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:705)
09-06 21:40:31.534 16426 16760 E k9      :      at java.io.InputStream.read(Inpu
tStream.java:162)
09-06 21:40:31.534 16426 16760 E k9      :      at java.io.BufferedInputStream.f
illbuf(BufferedInputStream.java:149)
09-06 21:40:31.534 16426 16760 E k9      :      at java.io.BufferedInputStream.r
ead(BufferedInputStream.java:234)
09-06 21:40:31.534 16426 16760 E k9      :      at com.fsck.k9.mail.filter.Peeka
bleInputStream.peek(PeekableInputStream.java:34)
09-06 21:40:31.534 16426 16760 E k9      :      at com.fsck.k9.mail.store.imap.I
mapResponseParser.readResponse(ImapResponseParser.java:41)
09-06 21:40:31.534 16426 16760 E k9      :      at com.fsck.k9.mail.store.imap.I
mapResponseParser.readResponse(ImapResponseParser.java:32)
09-06 21:40:31.534 16426 16760 E k9      :      at com.fsck.k9.mail.store.imap.I
mapResponseParser.readStatusResponse(ImapResponseParser.java:73)
09-06 21:40:31.534 16426 16760 E k9      :      at com.fsck.k9.mail.store.imap.I
mapConnection.executeSimpleCommand(ImapConnection.java:307)
09-06 21:40:31.534 16426 16760 E k9      :      at com.fsck.k9.mail.store.imap.I
mapConnection.executeSimpleCommand(ImapConnection.java:288)
09-06 21:40:31.534 16426 16760 E k9      :      at com.fsck.k9.mail.store.imap.I
mapStore$ImapFolder.executeSimpleCommand(ImapStore.java:724)
09-06 21:40:31.534 16426 16760 E k9      :      at com.zegoggles.smssync.mail.Ba
ckupImapStore$BackupFolder.access$200(BackupImapStore.java:140)
09-06 21:40:31.534 16426 16760 E k9      :      at com.zegoggles.smssync.mail.Ba
ckupImapStore$BackupFolder$1.search(BackupImapStore.java:164)
09-06 21:40:31.534 16426 16760 E k9      :      at com.fsck.k9.mail.store.imap.I
mapStore$ImapFolder.search(ImapStore.java:1259)
09-06 21:40:31.534 16426 16760 E k9      :      at com.zegoggles.smssync.mail.Ba
ckupImapStore$BackupFolder.getMessages(BackupImapStore.java:168)
09-06 21:40:31.534 16426 16760 E k9      :      at com.zegoggles.smssync.service
.RestoreTask.restore(RestoreTask.java:105)
09-06 21:40:31.534 16426 16760 E k9      :      at com.zegoggles.smssync.service
.RestoreTask.doInBackground(RestoreTask.java:85)
09-06 21:40:31.534 16426 16760 E k9      :      at com.zegoggles.smssync.service
.RestoreTask.doInBackground(RestoreTask.java:47)
09-06 21:40:31.534 16426 16760 E k9      :      at android.os.AsyncTask$2.call(A
syncTask.java:295)
09-06 21:40:31.534 16426 16760 E k9      :      at java.util.concurrent.FutureTa
sk.run(FutureTask.java:237)
09-06 21:40:31.534 16426 16760 E k9      :      at java.util.concurrent.ThreadPo
olExecutor.runWorker(ThreadPoolExecutor.java:1113)
09-06 21:40:31.534 16426 16760 E k9      :      at java.util.concurrent.ThreadPo
olExecutor$Worker.run(ThreadPoolExecutor.java:588)
09-06 21:40:31.534 16426 16760 E k9      :      at java.lang.Thread.run(Thread.j
ava:818)
09-06 21:40:31.542 16426 16760 E SMSBackup+: error
09-06 21:40:31.542 16426 16760 E SMSBackup+: com.fsck.k9.mail.MessagingException
: IO Error
09-06 21:40:31.542 16426 16760 E SMSBackup+:    at com.fsck.k9.mail.store.imap.I
mapStore$ImapFolder.ioExceptionHandler(ImapStore.java:2087)
09-06 21:40:31.542 16426 16760 E SMSBackup+:    at com.fsck.k9.mail.store.imap.I
mapStore$ImapFolder.search(ImapStore.java:1288)
09-06 21:40:31.542 16426 16760 E SMSBackup+:    at com.zegoggles.smssync.mail.Ba
ckupImapStore$BackupFolder.getMessages(BackupImapStore.java:168)
09-06 21:40:31.542 16426 16760 E SMSBackup+:    at com.zegoggles.smssync.service
.RestoreTask.restore(RestoreTask.java:105)
09-06 21:40:31.542 16426 16760 E SMSBackup+:    at com.zegoggles.smssync.service
.RestoreTask.doInBackground(RestoreTask.java:85)
09-06 21:40:31.542 16426 16760 E SMSBackup+:    at com.zegoggles.smssync.service
.RestoreTask.doInBackground(RestoreTask.java:47)
09-06 21:40:31.542 16426 16760 E SMSBackup+:    at android.os.AsyncTask$2.call(A
syncTask.java:295)
09-06 21:40:31.542 16426 16760 E SMSBackup+:    at java.util.concurrent.FutureTa
sk.run(FutureTask.java:237)
09-06 21:40:31.542 16426 16760 E SMSBackup+:    at java.util.concurrent.ThreadPo
olExecutor.runWorker(ThreadPoolExecutor.java:1113)
09-06 21:40:31.542 16426 16760 E SMSBackup+:    at java.util.concurrent.ThreadPo
olExecutor$Worker.run(ThreadPoolExecutor.java:588)
09-06 21:40:31.542 16426 16760 E SMSBackup+:    at java.lang.Thread.run(Thread.j
ava:818)
09-06 21:40:31.542 16426 16760 E SMSBackup+: Caused by: java.net.SocketTimeoutEx
ception: Read timed out
09-06 21:40:31.542 16426 16760 E SMSBackup+:    at com.android.org.conscrypt.Nat
iveCrypto.SSL_read(Native Method)
09-06 21:40:31.542 16426 16760 E SMSBackup+:    at com.android.org.conscrypt.Ope
nSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:705)
09-06 21:40:31.542 16426 16760 E SMSBackup+:    at java.io.InputStream.read(Inpu
tStream.java:162)
09-06 21:40:31.542 16426 16760 E SMSBackup+:    at java.io.BufferedInputStream.f
illbuf(BufferedInputStream.java:149)
09-06 21:40:31.542 16426 16760 E SMSBackup+:    at java.io.BufferedInputStream.r
ead(BufferedInputStream.java:234)
09-06 21:40:31.542 16426 16760 E SMSBackup+:    at com.fsck.k9.mail.filter.Peeka
bleInputStream.peek(PeekableInputStream.java:34)
09-06 21:40:31.542 16426 16760 E SMSBackup+:    at com.fsck.k9.mail.store.imap.I
mapResponseParser.readResponse(ImapResponseParser.java:41)
09-06 21:40:31.542 16426 16760 E SMSBackup+:    at com.fsck.k9.mail.store.imap.I
mapResponseParser.readResponse(ImapResponseParser.java:32)
09-06 21:40:31.542 16426 16760 E SMSBackup+:    at com.fsck.k9.mail.store.imap.I
mapResponseParser.readStatusResponse(ImapResponseParser.java:73)
09-06 21:40:31.542 16426 16760 E SMSBackup+:    at com.fsck.k9.mail.store.imap.I
mapConnection.executeSimpleCommand(ImapConnection.java:307)
09-06 21:40:31.542 16426 16760 E SMSBackup+:    at com.fsck.k9.mail.store.imap.I
mapConnection.executeSimpleCommand(ImapConnection.java:288)
09-06 21:40:31.542 16426 16760 E SMSBackup+:    at com.fsck.k9.mail.store.imap.I
mapStore$ImapFolder.executeSimpleCommand(ImapStore.java:724)
09-06 21:40:31.542 16426 16760 E SMSBackup+:    at com.zegoggles.smssync.mail.Ba
ckupImapStore$BackupFolder.access$200(BackupImapStore.java:140)
09-06 21:40:31.542 16426 16760 E SMSBackup+:    at com.zegoggles.smssync.mail.Ba
ckupImapStore$BackupFolder$1.search(BackupImapStore.java:164)
09-06 21:40:31.542 16426 16760 E SMSBackup+:    at com.fsck.k9.mail.store.imap.I
mapStore$ImapFolder.search(ImapStore.java:1259)
09-06 21:40:31.542 16426 16760 E SMSBackup+:    ... 9 more
09-06 21:40:31.546  1715  4049 D WifiService: releaseWifiLockLocked: WifiLock{SM
SBackup+ type=3 binder=android.os.BinderProxy@1fda5bb}
09-06 21:40:31.561 16426 16426 D SMSBackup+: finished (RestoreStateChanged{state
=ERROR, currentRestoredCount=0, itemsToRestore=0, actualRestoredCount=0, duplica
teCount=0}/0)
09-06 21:40:31.570 16426 16426 D SMSBackup+: restoring SMS provider com.google.a
ndroid.apps.messaging
09-06 21:40:31.571  1715  3819 I ActivityManager: START u0 {act=android.provider
.Telephony.ACTION_CHANGE_DEFAULT cmp=com.android.settings/.SmsDefaultDialog (has
 extras)} from uid 10200 on display 0
09-06 21:40:31.588 16426 16426 D SMSBackup+: stopping service, stateRestoreState
Changed{state=ERROR, currentRestoredCount=0, itemsToRestore=0, actualRestoredCou
nt=0, duplicateCount=0}
09-06 21:40:31.658  2801  2801 W Binder_3: type=1400 audit(0.0:1156): avc: denie
d { ioctl } for path="socket:[143072]" dev="sockfs" ino=143072 ioctlcmd=7704 sco
ntext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_sock
et permissive=0
09-06 21:40:31.658  2801  2801 W Binder_3: type=1400 audit(0.0:1157): avc: denie
d { ioctl } for path="socket:[143072]" dev="sockfs" ino=143072 ioctlcmd=7704 sco
ntext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_sock
et permissive=0
09-06 21:40:31.705  1715  1733 I ActivityManager: Displayed com.android.settings
/.SmsDefaultDialog: +99ms
09-06 21:40:36.818 11415 11447 I PlayCommon: [810] com.google.android.play.a.l.e
(787): Preparing logs for uploading
09-06 21:40:36.818 11415 11447 I PlayCommon: [810] com.google.android.play.a.l.e
(789): No file ready to send
09-06 21:40:37.252 11415 11496 I PlayCommon: [823] com.google.android.play.a.l.e
(787): Preparing logs for uploading
09-06 21:40:37.252 11415 11496 I PlayCommon: [823] com.google.android.play.a.l.e
(789): No file ready to send
09-06 21:40:37.320 11415 11493 I PlayCommon: [820] com.google.android.play.a.l.e
(787): Preparing logs for uploading
09-06 21:40:37.320 11415 11493 I PlayCommon: [820] com.google.android.play.a.l.e
(789): No file ready to send
09-06 21:40:37.330 11415 11495 I PlayCommon: [822] com.google.android.play.a.l.e
(787): Preparing logs for uploading
09-06 21:40:37.330 11415 11494 I PlayCommon: [821] com.google.android.play.a.l.e
(787): Preparing logs for uploading
09-06 21:40:37.330 11415 11495 I PlayCommon: [822] com.google.android.play.a.l.e
(789): No file ready to send
09-06 21:40:37.330 11415 11494 I PlayCommon: [821] com.google.android.play.a.l.e
(789): No file ready to send
```

**Comment by burtpolson** [comment] 2017-06-27 23:12
I see several discussions directed to 675, but no fix. Please advise.

**Comment by LittleTimmyHartwell** [comment] 2017-12-10 01:08
Agreed. It appears all support is down for this app.

**Comment by jberkel** [comment] 2017-12-10 13:31
It's a timeout error, from the server. How many items are you trying to restore? You can also try the beta version which has some improvements.

**Comment by korn16rtl3** [comment] 2017-12-14 15:17
I have just updated to the beta version of sms backup+ and no change, I am also having the same issues as described here on a Samsung Galaxy S5  with android version 4.4.2 I'm curious if some Google security settings might be causing these issues?

**Comment by korn16rtl3** [comment] 2017-12-14 15:19
I would also like to note that when I turn the log on and try to restore nothing is kept in the log

**Comment by jberkel** [comment] 2017-12-20 21:08
There's another beta now (1.5.11-beta7) which you can try

**Comment by nikkib1181** [comment] 2018-07-14 17:20
I am having the same problem with the restore io error message. I have a little over 6000 messages i would like to restore and I see no resolution anywhere on this thread. My messages are also being backed up in the incorrect order of date received. Please help.

**Comment by jcrben** [comment] 2018-07-14 18:13
@nikkib1181 what version? Anyhow, see https://github.com/jberkel/sms-backup-plus#faq-restore-many-messages - restoring tons of messages is not really supported.

I leave old messages in my email - restoring them to my phone seems to be more trouble than it's worth.

@jberkel I think we should stick to closing issues with restoring thousands of messages and strongly recommend the advice at https://github.com/jberkel/sms-backup-plus#faq-restore-partial

**Comment by nikkib1181** [comment] 2018-07-14 18:36
Thank you so much for your response. I'm using version 1.5.11. What if I restore messages from just one number? Am I able to do that?

And what about my time stamp and message order being incorrect? Is there a solution for that?

Many thanks!

**Comment by jcrben** [comment] 2018-07-14 18:59
You could try this https://github.com/jberkel/sms-backup-plus#faq-restore-partial:
> If you have a lot of messages backed up (let's say over 5000) restoring can be very slow, especially if you're only interested in the most recent messages.
> A workaround is to use the Gmail web interface (or an IMAP email client) to move the bulk of the messages to another label in Gmail (e.g. SMSARCHIVED), and only keep a few hundred or so messages in the SMS label.

As far as the timestamps issue, can you open another issue? looks like a duplicate of https://github.com/jberkel/sms-backup-plus/issues/94 - we have an link about it in the Table of Contents but it's broken https://github.com/jberkel/sms-backup-plus/commit/b35efe23aefb4943b8c96c72dde3d3344b44b9fd#diff-04c6e90faac2675aa89e2176d2eec7d8R346

**Comment by kurahaupo** [comment] 2019-11-09 09:33
@joshuatly can you use the partial restoration method advised above?

There's also a new beta version if you would like to try that.

The heart of the matter would appear to be this log line:

    09-06 21:40:31.534 16426 16760 E k9      : java.net.SocketTimeoutException: Read timed out

which is almost certainly caused by the large number of messages involved.

**Comment by kurahaupo** [comment] 2020-04-27 03:07
no response, closing issue

**Closed by kurahaupo** 2020-04-27 03:07 UTC
Labels: restore
