### ISSUE TITLE
Trying to Restore Messages Can't Due to IO Error

### ISSUE THREAD

**Issue by idealcalvin** [jberkel/sms-backup-plus#760] opened 2017-06-13 05:28 UTC
I just did a factory reset and  am attempting to restore message on Galaxy Pixel XL. 

SMSB+ set as default messaging app
Backup stored on Gmail account
After pressing Restore, shows "Working" and "Calculating..."
After about 30-40 seconds, shows "Error" and "Error during backup/restore: IO Error"
Pop notification appears "Change messaging app?; Do you want to use Messages instead of SMSB+ as your default messaging app?"
I varied the number of messages to retrieve resulting in the same error.
I've reviewed previous threads and didn't see any solutions on this specific issue. If I missed it please redirect (and forgive) me. Any help would be appreciated.

**Comment by parker5635** [comment] 2017-06-27 21:39
[675](https://github.com/jberkel/sms-backup-plus/issues/675)

**Comment by korn16rtl3** [comment] 2017-12-14 15:14
I'm also having a very similar issue, I can not seem to restore even running the latest beta as of writing, is it possible Gmail security is part of this issue? I keep getting an i/o error but I can backup my messages. Any idea what the issue might be? I'm running android 4.4.2 on a Samsung Galaxy S5

**Comment by jberkel** [comment] 2017-12-19 21:37
Duplicate of #675

**Closed by jberkel** 2017-12-19 21:37 UTC
