### ISSUE TITLE
Incorrect MMS Recipient labelling

### ISSUE THREAD

**Issue by aluminumfreeze** [jberkel/sms-backup-plus#1056] opened 2021-02-12 19:30 UTC
### Expected behaviour

Senders and recipients of Google Messages for Android MMS are correctly labeled in all SMS Backup+ backups in Gmail

### Actual behaviour

When an MMS message (like a photo) is sent through Google Messages for Web, it syncs back to Google Messages for Android. When SMS Backup+ backs up this MMS from the Android, it will incorrectly identify the recipient as the sender (user will be identified as both sender and recipient). Only happens to MMS not SMS.

### Steps to reproduce the behaviour

1. Send an MMS in Google Messages for Web
2. Check that the sent MMS has synced to Google Messages for Android
3. Initiate a backup with SMS Backup+ for Android
4. Check the backed up MMS in Gmail: the recipient is incorrectly listed as the sender (user has been identified as both sender and recipient)(only happens to MMS not SMS)

### Please specify the following:

* Android version - 11 Build RQ1A.210205.004 Security Update February 5, 2021
* Phone model / brand - Google Pixel 3XL
* SMS Backup+ version installed - 1.5.11
* Messaging app - Google Messages

**Comment by kurahaupo** [comment] 2021-02-14 08:17
@aluminumfreeze this looks like a duplicate of #390. If you think that it's different please let me know and I'll reopen this ticket.

@jberkel Although the symptoms differ slightly, they could both be caused by incorrect assumptions about the order of addresses within an MMS. (This only applies to MMS because only MMS supports "group chat".)

**Closed by kurahaupo** 2021-02-14 08:17 UTC
Labels: mms

**Comment by aluminumfreeze** [comment] 2021-02-14 14:52
Hi - Thanks for getting back to me. My ticket is specific to sending an MMS
through Google Messages for Web <https://messages.google.com/>. As I
described in my report, when an MMS sent through Google Messages for Web is
synced back to Google Messages for Android
<https://play.google.com/store/apps/details?id=com.google.android.apps.messaging&hl=en>,
Google Messages for Android gets the sender and recipient right, but when
SMS Backup+ pulls this message from Google Messages for Android, the MMS
recipient is mislabeled as the sender. MMS sent from Google Messages for
Android do not have this problem, the problem is only when sent from Google
Messages for Web, which then syncs back to Google Messages for
Android, which is then picked up by SMS Backup+. The ticket you refer to
was created in 2013 before Google Messages for Web even existed. I have no
example of an error when working with MMS in Google Messages for Android.

Because Google Hangouts support for SMS is ending
<https://support.google.com/fi/answer/9984024?co=GENIE.Platform%3DAndroid&hl=en>
in
March, users are starting to use Google Messages for Web instead. In fact,
the end of SMS support in Google Hangouts is the cause of my return to SMS
Backup+, since Hangouts will no longer be able to automatically put my SMS
in my Gmail. It's great to see SMS Backup+ still active after all these
years. Other users leaving Google Hangouts may turn to you as well. Google
Hangouts support for SMS ends in March and it will be renamed Google Meet
and Chat. The Chat functionality will be limited to GSuite (enterprise)
users. For anyone like me using Hangout to keep SMS in Gmail all these
years, SMS Backup+ is the best way to keep doing so.

I love SMS Backup+.

Thank you,

Anthony

**Comment by aluminumfreeze** [comment] 2021-02-14 15:25
Whelp, this morning I'm seeing the issue when sending MMS through Google
Messages for Android. Didn't happen when I tested yesterday but it's
happening now. For any MMS, SMS Backup+ lists sender as recipient.
