### ISSUE TITLE
Auto Backup is not working on OnePlus 9

### ISSUE THREAD

**Issue by robcampbell95** [jberkel/sms-backup-plus#1065] opened 2021-07-07 23:30 UTC
Before you report your issue, please consider perusing the [https://github.com/jberkel/sms-backup-plus#faq](FAQ) and searching the issues page to see if it has already been reported.

### Expected behaviour
Auto backup would backup sms and calls one minute after they happen.

### Actual behaviour
Backup only occurs when I manually run it

### Steps to reproduce the behaviour
Set your auto backup settings (mine is set to 30min/1min)

### Please specify the following:

* Android version 11
* Phone model / brand OnePlus 9
* SMS Backup+ version installed 16.0-BETA2
* Messaging app Google Messenges (Beta)

**Comment by kurahaupo** [comment] 2021-07-08 22:19
Thanks for the report.

Duplicate of #758

**Closed by kurahaupo** 2021-07-08 22:19 UTC
Labels: schedule
