### ISSUE TITLE
Having an IO error uploading to SMs+

### ISSUE THREAD

**Issue by hubes99** [jberkel/sms-backup-plus#1100] opened 2023-07-29 01:35 UTC
### Expected behaviour

Getting the I/o error 

### Actual behaviour

Here is the log

/storage/emulated/0/Android/
data/com.zegoggles.smssync/fil..
07-28 16:06 Backing up (4 SMS, 32017 MMS, 0 call
log)
07-28 16:06 Using config: BackupConfigfimap
=BackuplmapStore(uri=imap+ssl+://PLAIN:
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXxXXXX@IMAP.gmail.com:993),
currentTry=0, maxltemsPerSync=-1
groupToBackup=ContactGroup(_id=-1,
type=EVERYBODY), backupType=MANUAL
debug=true, typesToBackup=[SMS, MMS])
07-28 16:12 BackupState (currentSyncedltems=70
itemsToSync=32021, backupType=MANUAL
exception=null, state=CANCELED_BACKUP>
07-28 16:12 Backup canceled
07-28 18:45 Backup requested (manual)
07-28 18:45 Starting backup (MANUAL)
07-28 18:45 Backing up (13 SMS, 31975 MMS, 0 call
log)
07-28 18:45 Using config: BackupConfig(imap
=BackuplmapStore(uri=imap+ss!+://PLAIN:
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXX@IMAP.gmail.com:993),
currentTry=0, maxltemsPerSync=-1
groupToBackup=ContactGroup(_id=-1,
type=EVERYBODY), backupType=MANUAL
debug=true, typesToBackup=[SMS, MMS])
07-28 19:21 General error: 10 Error (exception:
com.fsck.k9.mail.MessagingException: I0 Error,
underlying=java.net.SocketException: Software
caused connection abort)
07-28 19:21 BackupState (currentSyncedltems=265,
itemsToSync=31972, backupType=MANUAL
exception=com.fsck.k9.mail.MessagingException: I0
Error, state=ERROR)
07-28 19:21 Backup finished
OK

### Android version

13 (2022)

### Phone brand

Samsung

### SMS Backup+ version

v1.5.11

**Comment by AlexHimself** [comment] 2023-09-13 22:16
This looks like a duplicate of #1095

**Comment by kurahaupo** [comment] 2024-04-15 02:21
@AlexHimself agreed

**Closed by kurahaupo** 2024-04-15 02:21 UTC
Labels: bug
