### ISSUE TITLE
[BUG] This app is blocked

### ISSUE THREAD

**Issue by paour** [jberkel/sms-backup-plus#1106] opened 2024-01-31 13:52 UTC
### Expected behaviour

When I trigger a backup, it should complete without error.

### Actual behaviour

SMS Backup+ reports the following error: `XOAuth authorization error. Please make sure you enabled IMAP in your Gmail account settings.`.

Play Services on my device displays a notification with the following alert:

![Screenshot_20240131-141311](https://github.com/jberkel/sms-backup-plus/assets/90963/14701afa-a2e8-4e9d-97e3-bbc0bd71f90e)

### Android version

11 (2020)

### Phone brand

OnePlus

### Phone model number

8T

### SMS Backup+ version

v1.6β

**Comment by paour** [comment] 2024-01-31 13:52
This looks like the end of the road. Even side-loaded, the app is blocked server-side by Google…

**Comment by pataquets** [comment] 2024-02-11 14:41
@paour #1102 stopped working?

**Comment by paour** [comment] 2024-02-11 14:43
> @paour #1102 stopped working?

Yes. I've been using app passwords forever because 2FA. I generated a new one when this cropped up, to no avail.

**Comment by marclaporte** [comment] 2024-02-11 17:22
Workaround: use a standard IMAP account (strong password always): https://github.com/jberkel/sms-backup-plus#usage-without-gmail-imap

**Comment by kurahaupo** [comment] 2024-02-13 03:10
"This app is blocked" occurs when an app uses a Google API.

The reason that using IMAP works is that although it's _provided_ by Google, it's not _defined_ by Google, and the IMAP does transmit any identification of the app. So the server cannot know which app is using the IMAP connection, and can't use that to decide to block it.

So the question is, which Google API _is_ being refused?

(My money would be on the contacts list API; I would test that by changing the default message format to include just the phone number and exclude the person's name.)

**Comment by BenJewell** [comment] 2024-02-23 01:26
Still works fine for me using IMAP. Was getting a lot of errors a couple weeks ago but seems to have resolved itself.

**Comment by kurahaupo** [comment] 2024-04-15 02:23
Appears to be a duplicate of #1046

**Closed by kurahaupo** 2024-04-15 02:23 UTC
Labels: duplicate, xoauth
