### ISSUE TITLE
Not all messages syncing

### ISSUE THREAD

**Issue by guardonduty** [jberkel/sms-backup-plus#858] opened 2018-03-28 22:44 UTC
Hello im posting due to the fact that i love the app but im having 1 major issue. None of my replys are saving unless is a photo. Ive reinstalled the app and my phone and still does the same thing.
Android 7.1.1
Samsung note 8 8.5 
1.5.10

**Comment by jberkel** [comment] 2018-03-29 08:09
Do you use Advanced Messaging / Google Hangouts or similar?

See 

https://github.com/jberkel/sms-backup-plus/#rich-communication-services

**Comment by guardonduty** [comment] 2018-03-29 12:14
Yes that's what i have. Thank u for reading my message. Cuase its not
working the way it should. I got all my received messages but not my sent

**Comment by guardonduty** [comment] 2018-03-29 12:17
No its the standard come with the phone messages. Not att not hangouts.

**Comment by jcrben** [comment] 2018-03-31 15:39
Can you try the beta? https://github.com/jberkel/sms-backup-plus#beta

**Comment by guardonduty** [comment] 2018-03-31 15:47
Neg.

**Comment by jcrben** [comment] 2018-03-31 17:03
@guardonduty no you haven't, or no you cannot? I would help out if you could test to see if it fixes the issue 😄

**Comment by guardonduty** [comment] 2018-03-31 17:35
No I do not have access to it in the store.

**Comment by jcrben** [comment] 2018-04-17 03:34
This looks like a duplicate of https://github.com/jberkel/sms-backup-plus/issues/872

We need someone to send us a log to get a better understanding of what's happening - if you can, please update to the beta and follow the instructions at https://github.com/jberkel/sms-backup-plus#i-want-to-file-a-bug-report-what-should-i-do to post a log

We can't reproduce so we can't help without more information.

**Closed by jcrben** 2018-04-17 03:34 UTC
Labels: backup
