### ISSUE TITLE
scheduled backup and Tasker 3rd party both not working

### ISSUE THREAD

**Issue by JoshFlory** [jberkel/sms-backup-plus#921] opened 2018-09-17 18:13 UTC
Before you report your issue, please consider perusing the [https://github.com/jberkel/sms-backup-plus#faq](FAQ) and searching the issues page to see if it has already been reported.

### Expected Behaviour 
Automated backups should run on the schedule selected, and after X time has passed when receiving a text.  3rd party app calls like Tasker should execute SMS Backup when the plugin is called.  *Manual backups work without issue

### Actual behaviour
When the schedule is enabled backups should be performed after the elapsed time (30 min) and after the elapsed time of a text message being received.  Also, when Tasker is used to call the 3rd party plugin to run backup, it should execute.  If manual backup is performed it works without issue.

In the log this error is often seen when calling from Tasker:
Backup requested (3rd party)
08-31 11:54 Backup skipped, no connectivity

### Steps to reproduce the behaviour
Does not work on Samsung S7 or S9 Note.  Set and enable scheduled backups, send texts to the phone from another device.  Wait for the period of time to elapse that should have triggered backups (two hours to test the 30 min schedule for example).

### Please specify the following:

* Android version 8.1.0
* Phone model / brand  Samsung Note 9
* SMS Backup+ version installed 1.5.11
*Textra 
[sms_backup_plus.log](https://github.com/jberkel/sms-backup-plus/files/2389707/sms_backup_plus.log)

**Comment by mrandreastoth** [comment] 2018-10-06 22:35
I hope this issue is top priority since not only does it completely void the app, but it also makes it the top battery-drainer.

**Comment by TjrGithub** [comment] 2019-04-02 00:11
Same issue, except it doesn't drain battery. The scheduler has never worked for the last 3 years.

LineageOS 15.1, latest FDroid smsbackup+.

**Comment by kurahaupo** [comment] 2021-07-08 22:42
Thanks everyone for the feedback.

Using the new Oreo JobScheduler API is on the roadmap.

I'm marking this as a duplicate of #758 just so we can track one issue and keep all the feedback in one place.

**Closed by kurahaupo** 2021-07-08 22:42 UTC
Labels: duplicate, schedule
