### ISSUE TITLE
Sms plus won't autobackup anymore

### ISSUE THREAD

**Issue by Luisruns** [jberkel/sms-backup-plus#957] opened 2019-05-31 03:43 UTC
Before you report your issue, please consider perusing the [https://github.com/jberkel/sms-backup-plus#faq](FAQ) and searching the issues page to see if it has already been reported.

### Please specify the following:

* Android version 9
* Samsung Galaxy S10+
* SMS Backup+ version installed 1.5.11
* Messaging app Verizon Message +
I attempt to manually back up, and it starts for a while and then automatically cancels itself.

**Comment by wuxxin** [comment] 2019-08-07 13:25
also affected: Google Pixel with Lineage 16 (Android 9), SMS Backup+ from fdroid Version 1.5.11
what is working: start manual backup
what is not working: automatic Backup (but selected)
what is greyed out: "Connect" (Verbinden in German) can not be selected

**Comment by kurahaupo** [comment] 2019-11-09 05:09
Duplicate of #954

**Closed by kurahaupo** 2019-11-09 05:09 UTC
Labels: schedule
