### ISSUE TITLE
SMS Backup+ will not auto backup

### ISSUE THREAD

**Issue by RodMyers** [jberkel/sms-backup-plus#507] opened 2014-12-14 13:34 UTC
AT&T/Straight Talk Samsung Galaxy S3 SGH-l747 (rooted), android 4.4.2 SMS Backup+ 1.5.5

This release for sure, nothing gets automatically backed up, as per the options selected.

The are no log entries, since nothing gets backed up

**Comment by RodMyers** [comment] 2015-01-08 17:10
SMS Backup+ 1.5.8 installed 2/6/2015
no auto backup with this release

**Comment by RodMyers** [comment] 2015-01-21 16:11
wow, time to look for a new program to back up SMS text. over a month, numerous updates, and appeaqrs noone cares

**Comment by jberkel** [comment] 2015-01-21 17:57
this bug has been around for a while, and i could never reproduce it locally. and without debug logs i cannot help you. sorry!

**Comment by RodMyers** [comment] 2015-01-21 18:43
Does the log file "need" to go to the external card?

**Comment by jberkel** [comment] 2015-01-23 08:53
with more recent versions of android it is not necessarily an external card. have you tried installing a filemanager on the phone ? do you see a directory called sdcard ? it should be in there.

**Comment by RodMyers** [comment] 2015-01-23 10:54
On Fri, 23 Jan 2015 00:54:03 -0800
Jan Berkel <notifications@github.com> wrote:

> with more recent versions of android it is not necessarily an
> external card. have you tried installing a filemanager on the phone ?
> do you see a directory called sdcard ? it should be in there.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/jberkel/sms-backup-plus/issues/507#issuecomment-71164172

With this email, I just checked again, was finally able to enable the
log file. 

I will get you a log file in the next few days

-- 
Rodney D. Myers <rdmyers.42@gmail.com>

They that can give up essential liberty to obtain a
little temporary safety deserve neither liberty nor safety.
        Ben Franklin - 1759

**Comment by RodMyers** [comment] 2015-01-26 01:06
Here is a copy of the log_file. it  only shows the manual backups.

Not sure where the config files are stored, to show what the settings are

**Comment by jberkel** [comment] 2015-01-26 12:14
don't see the log file, did you attach it correctly?

**Comment by RodMyers** [comment] 2015-01-26 12:22
On Sun, 25 Jan 2015 20:06:05 -0500
rodney myers <rdmyers.42@gmail.com> wrote:

> Here is a copy of the log_file. it  only shows the manual backups.
> 
> Not sure where the config files are stored, to show what the settings
> are
> 
> On Fri, Jan 23, 2015 at 3:54 AM, Jan Berkel <notifications@github.com>
> wrote:
> 
> > with more recent versions of android it is not necessarily an
> > external card. have you tried installing a filemanager on the
> > phone ? do you see a directory called sdcard ? it should be in
> > there.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/jberkel/sms-backup-plus/issues/507#issuecomment-71164172>

Alright, lets try again.

it looks like its' attached this time

-- 
Rodney D. Myers <rdmyers.42@gmail.com>

They that can give up essential liberty to obtain a
little temporary safety deserve neither liberty nor safety.
        Ben Franklin - 1759

**Comment by jberkel** [comment] 2015-01-26 12:36
sorry, still don't see it

**Comment by RodMyers** [comment] 2015-01-26 14:23
OKay, i'll copy/paste here

++++++++++ begin log file ++++++++++
01-23 16:05 Backup requested (manual)
01-23 16:05 Starting backup (MANUAL)
01-23 16:05 Backing up (9 SMS, 0 MMS, 0 call log)
01-23 16:05 Backing up (9 SMS, 0 MMS, 0 call log)
01-23 16:05 Backup finished
01-23 21:25 Backup requested (manual)
01-23 21:25 Starting backup (MANUAL)
01-23 21:25 Backing up (28 SMS, 0 MMS, 0 call log)
01-23 21:25 Backing up (28 SMS, 0 MMS, 0 call log)
01-23 21:25 Backup finished
01-25 08:00 Backup requested (manual)
01-25 08:00 Starting backup (MANUAL)
01-25 08:00 Backing up (14 SMS, 0 MMS, 0 call log)
01-25 08:00 Backing up (14 SMS, 0 MMS, 0 call log)
01-25 08:00 Backup finished
01-25 09:23 Backup requested (manual)
01-25 09:23 Starting backup (MANUAL)
01-25 09:23 Skipped (no items found)
01-25 09:23 Backup finished
01-25 20:00 Backup requested (manual)
01-25 20:00 Starting backup (MANUAL)
01-25 20:00 Backing up (1 SMS, 0 MMS, 0 call log)
01-25 20:00 Backing up (1 SMS, 0 MMS, 0 call log)
01-25 20:00 Backup finished
++++++++++ end log file ++++++++++

Note, there are no automatic backups over the weekend. All manual. I have
the preferences set to back up after 3 minutes

**Comment by jberkel** [comment] 2015-02-03 09:32
weird, it doesn't even get triggered. have you tried setting it to a regular schedule ?

**Comment by RodMyers** [comment] 2015-02-03 10:55
On Tue, 03 Feb 2015 01:32:23 -0800
Jan Berkel <notifications@github.com> wrote:

> weird, it doesn't even get triggered. have you tried setting it to a
> regular schedule ? 
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/jberkel/sms-backup-plus/issues/507#issuecomment-72619626

exactly.

let me know what you need, and i'll try to get it accomplished

-- 
Rodney D. Myers <rdmyers.42@gmail.com>

They that can give up essential liberty to obtain a
little temporary safety deserve neither liberty nor safety.
        Ben Franklin - 1759

**Comment by MikeHunter76** [comment] 2015-02-16 08:25
I'd like to add my issue to this excisting because it seams to be nearly the same problem.

The regular schedule work sometimes.
The backup triggered by hand will only work if there a entries in
1. the call log or
2. the sms app

Right now, it seams to be impossible to force a backup of the whatsapp entries (even if the device is rooted and tri-Crypt is installed.)

Maybe this is caused by the same routine as the issue above.
Thanks for your help in advance.

**Comment by ssviro** [comment] 2015-03-19 03:53
March 8th was the last time this app automatically backed up. It has always worked great until then. Nothing on my end has changed-I haven't installed new apps, I haven't changed phones ,  etc, so it's strange that it just stopped. Manual back ups still work but it won't automatically back up. I tried resetting and double checking the settings, so I'm not sure what to do next.

**Comment by Deedadee** [comment] 2015-07-14 15:33
Has this issue ever been resolved?  I, too, also started having problems with the app AUTOMATICALLY backing up, with it working about 5% of the time.  It only occasionally gives the red exclamation point to indicate a problem has occurred.  The only way I know this is happening is when going into the app to see the last backup day/time and it's mostly 2-3 days by the time I see it.  Then I do a manual backup that only takes pace IF I DIDNT DELETE the last couple days worth of texts as Im used to doing because i thought the app was working.  I have actually had this app installed for a few years because I cant download any more updates due to the download sites not supporting Froyo any longer.  I DID have the fairly recent problem due to google/imap changes, but that was an easy fix.  But this app's recent problem is obviously not due to antpy updates located in the DOWNLOAD for sure, because its happening to my older installed version, too.  Was my most valuable app before this, now just giving a false sense of security and I need to find a replacement app backward compatible with froyo if this isnt fixable.

**Comment by ssviro** [comment] 2015-07-14 20:25
Hello,

No, it has not been resolved. It seems as though it does it at times, but
not at the correct interval. For example I just checked and the last time
it backed up was two days ago even though my setting is for 2 hours regular
schedule and 1 minute for incoming.

Thanks

**Comment by jberkel** [comment] 2015-07-16 12:44
i'm aware of this problem, the only real fix for this is to switch to android's syncmanager to do the backup scheduling. i think there's an open issue around that. i hope i'll get it into the next major release (1.6)

**Comment by JesusHChrist** [comment] 2015-08-05 03:22
This app is terrible, I refuse to ever use it again!! I uninstalled the app from my Android phone bc it stopped working and when I tried to reinstall it from the play store it was gone! Good riddance, don't bother putting that POS app back in the play store!!!

**Comment by dg4u** [comment] 2015-09-02 17:50
JesusHChrist, I'm thankful that the SMS Backup Plus app exists and that Jan has written it and shared it with us. It has been serving me well and reliably for about a year and a half (when I first started using it on my new cell phone). I'm not aware of a better SMS backup program; and many other knowledgeable reviews regard it as the best. 

Of course it has it's imperfections, like all of us (smile), but Jan said he was aware of the problem and is willing to address it in the next major version. Perhaps you could contribute something positive to help improve it (like praise or financial support/incentive), or write your own app and give it away for free if you don't like what Jan is doing. 

Either way, your angry venting is not at all helpful and certainly not Christlike.

**Comment by DickYue** [comment] 2016-02-04 15:39
First, i used this app form 3years ago, thx for developer.
Last auto backup on Jan 28, 2015
LG nexus 5 D820
Android 6.0.1
Version 1.5.10

**Comment by jberkel** [comment] 2016-02-07 14:37
closed in favour of #572

**Closed by jberkel** 2016-02-07 14:37 UTC

**Comment by fkbreitl** [comment] 2016-04-14 14:34
Seems like I have the same problem.

**Comment by fkbreitl** [comment] 2016-04-20 13:40
As it turns out I could fix the auto backup by disabling the smart manager optimization for SMS Backup+.
Now the automatic backup happens regularly again as expected.
