### ISSUE TITLE
Feature request: separate backups for dual SIM phones

### ISSUE THREAD

**Issue by yurks** [jberkel/sms-backup-plus#1007] opened 2019-12-29 00:34 UTC
Highly useful to have a possibility of setting up different IMAP folders (or even accounts) for backup calls and sms came from different SIM cards or SIP accounts.

**Comment by kurahaupo** [comment] 2020-01-03 03:38
This appears to be a duplicate of #598 which is requesting substantially the same features.

**Closed by kurahaupo** 2020-01-03 03:38 UTC
