### ISSUE TITLE
Problem with restoration of non-english messages

### ISSUE THREAD

**Issue by lefman** [jberkel/sms-backup-plus#521] opened 2015-01-09 10:49 UTC
Hi and congrats for your very helpful app. I have used the app in the past and worked perfectly.
This time, I backed up my messages from a Samsung galaxy S2. I checked the messages on gmail and they showed up nicely. Then I tried to restore the messages on my new LG G3. The restoration was successfull but I noticed that non-english charachters (actually greek) characters do not appear correctly. When I click view original message in gmail, I notice that the sms content is exactly the same with what appears on my phone. It seems that while the browser (chrome) does the conversion correctly, the messaging app doesn't. It is definetely an encoding issue. I found that any greek character that does not have an english equivalent is represented with its utf8 code when performing the backup. While chrome does the translation nicely when showing the message, the messaging app does not. Any suggestions on how to fix this issue. I tried changing the encoding in the messages app but it didn't work. I also tried using hangouts to display the message but the issue is still there. Is the fact that not all characters are transformed to unicode when doing the backup the problem?

**Comment by jberkel** [comment] 2015-01-09 23:52
duplicate of #519

**Closed by jberkel** 2015-01-09 23:52 UTC

**Comment by lefman** [comment] 2015-01-10 00:16
Thanks for the immediate reply! Works perfectly again!
