### ISSUE TITLE
Backups keep cancelling 

### ISSUE THREAD

**Issue by brendamd** [jberkel/sms-backup-plus#938] opened 2019-02-11 20:52 UTC
### Expected behaviour
Backups of SMS and calls to automatically happen as scheduled. 

### Actual behaviour
Zero backups since August 2018 (I've just realised!) Reset doesn't help. App is not being battery optimised. Disconnect and reconnect account doesn't help. Gmail labels are in correct case etc. 

### Please specify the following:

* Android version is 9
* Phone model / brand is Huawei Mate 10 Pro
* SMS Backup+ version installed is 1.5.11 (just signed up for beta to see if that helps) 
* Messaging app is now Texta but was stock Mate Pro until a month ago. Backup not working on either nor on calls. 

https://drive.google.com/file/d/1Kybgw5mF40UYGgTWiIuCRbFP9foB5u2M/view?usp=drivesdk

**Comment by kurahaupo** [comment] 2019-11-09 09:12
(text in image reads)

### /storage/emulated/0/Android/data/com.zego&hellip;

    12-02 07:17 Backup up (1769 SMS, 86 MMS, 495 call log)
    12-02 07:17 Using config: BackupConfig{imap=BackupImapStore{uri=imap+ssl+://XOAUTH2:XXXXX[...]XXXXX@imap.gmail.com:992}, currentTry=1, maxItemsPerSync=-1, groupToBackup=ContactGroup{_id=-1, type=EVERYBODY}, backupType=REGULAR, debug=true, typesToBackup=[SMS, MMS, CALLLOG]}
    12-02 07:17 BackupState{currentSynedItems=0, itemsToSync=0, backupType=REGULAR, exception=null, state=CANCELED_BACKUP}
    12-02 17:17 Backup canceled

@brendamd 
I note that this log records the attempted use of XOAUTH2 which is no longer supported.
Does it work if configured to use IMAP?

**Comment by brendamd** [comment] 2019-11-13 23:49
Hi,

I have enabled IMAP in Gmail but get authorisation errors. I then
disconnected the account from the app to reconnect it and get the attached
screenshot errors (I can't reconnect the account at all now).

What do we do to fix this?

Brenda

**Comment by kurahaupo** [comment] 2019-12-20 00:40
Did you switch the settings in SMS Backup+ to IMAP as well?
There are instructions at #972.

**Comment by kurahaupo** [comment] 2019-12-20 00:42
Closing as duplicate of (and resolved by) #972.
Please reopen this ticket #938 if you need further assistance.

**Closed by kurahaupo** 2019-12-20 00:42 UTC
Labels: awaiting response, duplicate, xoauth
