### ISSUE TITLE
Not compatible with FastMail/JMAP? App crashes upon trying to backup.

### ISSUE THREAD

**Issue by chetcuti** [jberkel/sms-backup-plus#688] opened 2016-10-29 04:20 UTC
I've been using and absolutely loving SMS Backup+ for years now, however I recently moved away from GMAIL to FastMail, who I just realized uses JMAP instead of IMAP, and now when I try to backup the app crashes and gives the error, "Unfortunately, SMS Backup+ has stopped".

Are there any plans for SMS Backup+ to support FastMail and/or JMAP?

---

I enabled the sync log so I could give more information, however since I started testing this nothing new has been getting written to the log. This is the only thing that has been written to the log, even though I've tried to backup many, many times.

10-28 11:59 Backup requested (manual)

10-28 11:59 Starting backup (MANUAL)

10-28 11:59 Backing up (4 SMS, 0 MMS, 7 call log)

10-28 11:59 Using config: BackupConfig{imap=BackupImapStore{uri=imap+tls://PLAIN:XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX@imap.fastmail.com:993}, skip=false, currentTry=0, maxItemsPerSync=- 1, groupToBackup=ContactGroup{_id=-1, type=EVERYBODY}, backupType=MANUAL, debug=true, typesToBackup=[SMS, MMS, CALLLOG]}

10-28 12:00 BackupState{currentSyncedItems=0, itemsToSync=0, backupType=MANUAL, exception=null, state =CANCELED_BACKUP}

10-28 12:00 Backup canceled

**Comment by jberkel** [comment] 2016-10-29 09:01
Thanks for the report, I'll check. But fastmail also supports plain IMAP, no?

**Comment by chetcuti** [comment] 2016-10-29 09:57
To be honest I'm not entirely sure what they are and aren't using, I find conflicting information whenever I try to dig into it. On their [server names and ports](https://www.fastmail.com/help/technical/servernamesandports.html) page they only list IMAP, but I've read some other information that makes it seem like they're running either JMAP or an IMAP/JMAP hybrid.

I don't think they're running (or allow connecting) to straight IMAP though, as I've tried for a very long time to get SMS Backup+ working with them and it just won't, but as soon as I try another IMAP account it works instantly. Regardless of the system they're using, it seems to be the reason that SMS Backup+ won't work with them.

I've actually submitted a support ticket with them to find out exactly what their system is using, and I'll let you know on this ticket as soon as I hear back.

**Comment by chetcuti** [comment] 2016-10-29 18:23
According to support they are indeed using plain IMAP and not JMAP or an IMAP/JMAP hybrid, however SMS Backup+ just doesn't want to work with their system. I've now tried 6 different IMAP accounts and FastMail is the only one the app has a problem with. It seems to connect and create the backup folders that I've specified in SMS Backup+, but then the app crashes and continues to crash every time I try to start the backup.

Oh well, it's unfortunate that I can't just use FastMail directly to backup my calls and text messages, but I've been able to get it figured out by using a different email account that gets pulled into FastMail and some incoming FastMail rules/filters.

Although FastMail doesn't have a free account they do offer a 30 day free trial, in case you wanted to test this for yourself.

**Comment by jberkel** [comment] 2016-10-29 18:28
I'm actually a FastMail user myself, so will be able to test easily.

**Comment by jberkel** [comment] 2016-11-01 22:13
@chetcuti I've just tried it with my FastMail account and everything worked fine there (only tested backup).

Can you install the latest beta and make sure the problem is still present there?

https://github.com/jberkel/sms-backup-plus/releases/tag/1.5.11-BETA3

**Comment by chetcuti** [comment] 2016-11-01 23:24
Your account worked? Hmm, that's very strange indeed. I just tried the latest beta, and although the app is no longer crashing when I try to backup, it still won't actually backup.

Here are the settings I'm using. Are yours the same?

Authentication: Plain text
Server address: imap.fastmail.com:993
Security: see below
Email: my @fastmail.com email address
Password: app specific password

Just in case, I've tried every security type, and here are the error messages for each:

SSL: IMAP authorization error. Make sure login and password are set correctly.
SSL (trust all): IMAP authorization error. Make sure login and password are set correctly.
TLS: Error during backup/restore: Unable to connect
TLS (trust all): Error during backup/restore: Unable to connect
None: Error during backup/restore: Unable to connect

**Comment by jberkel** [comment] 2016-11-02 08:37
My config:

Authentication: Plain text
Server address: mail.messagingengine.com:993
Security: SSL
Email: my email
Password: app specific password

Only difference I see is the server address, maybe try with `mail.messagingengine.com:993`.

**Comment by chetcuti** [comment] 2016-11-02 17:26
Even with the other server address it's still not working, I still get the error, "IMAP authorization error. Make sure login and password are set correctly."

FastMail says that there's nothing on their end that should be causing this, and suggested that I set you up with a temporary password (with calendar access only) so you can test the connection yourself, which is something I would be open to if you want to continue to test this. If it doesn't work from your phone it's my FastMail account that's the issue, and if it does work it's my phone that's the issue.

If you want to give this a try just let me know.

**Comment by jberkel** [comment] 2016-11-02 18:12
Which access permissions did you pick? you'll need IMAP for backup to work, not calendar.


Ligado 2 de novembro de 2016 às 18:26:13, Greg Chetcuti (notifications@github.com(mailto:notifications@github.com)) escreveu:

**Comment by chetcuti** [comment] 2016-11-02 20:41
I usually use full access ("Mail, Contacts & Calendars"). Giving calendar-only access was just FastMail's suggestion for having a 3rd party do testing with my account, since it will allow them to test the connection but not be able to do anything.

**Comment by jberkel** [comment] 2016-11-02 20:48
Which means the calendar-only access would not be useful for testing. Sorry I'm running out of ideas. Maybe try the exact same password from another application?

**Comment by chetcuti** [comment] 2016-11-02 21:37
As much as I would love to be able to give full access to my account for testing, I'm becoming a bit of a privacy junkie these days (hence the switch from GMAIL to FastMail) so I just can't bring myself to do it. Don't feel too bad though, there's literally nobody on this planet I would give access to (not even my wife or best friends :P).

So if calendar access isn't enough to test the connection, I guess I'm out of ideas as well. Maybe I'll see if a friend will let me use their Android temporarily to see if I can get this working.

**Comment by jberkel** [comment] 2016-11-02 21:43
Sure, I completely understand. Hope you manage to get it to work!

**Comment by chetcuti** [comment] 2018-02-26 01:02
It's been a _bit_ of time since I first reported this issue, and I'm not exactly sure what's changed, but this is now working!

**My settings are:**
Authentication: Plain text
Server address: mail.messagingengine.com:993
Security: SSL
Username: (username I use to login to FastMail)
Password: (app-specific password that was setup specifically for SMS Backup+)

So basically the same settings as before, but now it's working.

**Comment by jberkel** [comment] 2018-02-26 04:58
great! closing this issue then.

**Closed by jberkel** 2018-02-26 04:58 UTC
