### ISSUE TITLE
Restore IO Error

### ISSUE THREAD

**Issue by ragnardannes66** [jberkel/sms-backup-plus#710] opened 2017-01-29 20:30 UTC
Successfully backed everything up, did a factory reset stock marshmallow (Dec 2016)

App will still backup any new messages I get/send, but if I try to restore it just says calculating and then goes to an IO Error

My first thought was that I have too many messages. I went into restore settings and set it to just 100 messages and still having the same issue.

**Comment by tmfa** [comment] 2017-02-19 18:05
I am having the same issue.  I can back up all SMS and MMS.  When I try to restore, I get an I/O error.  Changing the number of texts to restore makes no difference.

**Comment by taps007** [comment] 2017-02-28 10:54
Yes I have exactly the same issue on my Pixel (7.1.1)

**Comment by parker5635** [comment] 2017-05-30 15:13
[675](https://github.com/jberkel/sms-backup-plus/issues/675)

**Comment by LittleTimmyHartwell** [comment] 2017-12-10 01:12
Same problem. LG TP450, Android 7

**Comment by jberkel** [comment] 2017-12-19 21:38
Duplicate of #675

**Closed by jberkel** 2017-12-19 21:38 UTC
