### ISSUE TITLE
Backups always fail with "Backup skipped, no connectivity" message unless done manually

### ISSUE THREAD

**Issue by FelisPuma** [jberkel/sms-backup-plus#761] opened 2017-06-15 01:53 UTC
Hey there. My backups work great if I manually press the backup button, but won't happen automatically. My log has a bunch of lines
`Backup requested (incoming)`
`Backup skipped, no connectivity`
`Backup finished`
over and over. I have a Galaxy S8 and power saving is disabled for the app.

Thanks!

**Comment by CoooolRaoul** [comment] 2017-06-18 15:12
Excr same problem for me on Galaxy S7
Always worked fine with my previous device (Moto X)

**Comment by CoooolRaoul** [comment] 2017-06-20 11:50
Unfortunately workaround doesn't work: still getting "no connectivity" errors in the log file even for entry logged as  "third party triggered"

**Comment by CoooolRaoul** [comment] 2017-07-12 15:20
Last closed issue were at 12 Nov 2016.
I'm afraid this project is not alive anymore

**Comment by jberkel** [comment] 2017-07-14 07:37
@CoooolRaoul how is the phone connected? Wifi/3G?

**Comment by CoooolRaoul** [comment] 2017-07-14 08:05
WiFi: I've scheduled 3 syncs each evening when at home. 
None has ever worked.

**Comment by jberkel** [comment] 2017-07-14 08:17
@CoooolRaoul does it work on a mobile connection?

**Comment by CoooolRaoul** [comment] 2017-07-14 08:28
I've to set up a test case: I forgot to mention that, even on Wifi, it work when screen is on.
For example, when manually launched with a Tasker shortcut to my "SMS Backup Sync" task, sync is successful.
Stay tuned, I'll be back

**Comment by CoooolRaoul** [comment] 2017-07-14 08:46
Here's my Tasker task used as test case:
```
Screen off sync sms (267)
	A1: System Lock 
	A2: Wait [ MS:0 Seconds:2 Minutes:0 Hours:0 Days:0 ] 
	A3: Send Intent [ Action:com.zegoggles.smssync.BACKUP Cat:None Mime Type: Data: Extra: Extra: Extra: Package: Class: Target:Broadcast Receiver ] 
	A4: Play Ringtone [ Type:Notification Sound:Beep Once Stream:5 ] 
```
That one works (on Wifi)
I'm afraid that the ""no connectivity" errors arise only when phone has been idle for a sufficient long delay

I've no battery saver tools or setting which will shut down network when idle (and the phone is still reachable: I'm using "Join" app which allow remote actions and that one responds always even when phone has been idle.

Here's a  [link to SMS Backup log ](https://pastebin.com/LSvpsgFh)if it can help
(BTW: mybe should be OK to have the log in english instead of phone default language)

**Comment by CoooolRaoul** [comment] 2017-07-14 09:19
To be complete, here's the daily backup Profile (which fails):
```
Profile: SMS Backup 
	Time: From 20:00 every 1h Till 23:00
	State: Wifi Connected [ SSID:* MAC:* IP:* Active:Yes ]
Enter: SMS Backup
	A1: Send Intent [ Action:com.zegoggles.smssync.BACKUP Cat:None Mime Type: Data: Extra: Extra: Extra: Package: Class: Target:Broadcast Receiver ] 
```

**Comment by jberkel** [comment] 2017-07-14 22:32
Hmm, that is strange. It is probably some powersaving mechanism, somewhere, Android got really aggressive about that. Have you tried the backup while running "Join" (supposing it does something to keep the network connection alive?)

**Comment by CoooolRaoul** [comment] 2017-07-15 07:01
Browsing the codes, I gues it's [here](https://github.com/jberkel/sms-backup-plus/blob/20949b1fdd38b7dc183f8f2de5d8b30484b3ed31/src/main/java/com/zegoggles/smssync/service/SmsBackupService.java#L168)  you check networkconnectivity. 

Which seem totally OK for me.
Really weird.

**Comment by jberkel** [comment] 2017-07-15 07:11
Yes, it's the recommended way, and haven't heard of any other problems with it. maybe I can create a version with some more debug logging for you.

**Comment by CoooolRaoul** [comment] 2017-07-15 07:33
>  haven't heard of any other problems with it
@FelisPuma , initial poster has this issue too.

> maybe I can create a version with some more debug logging for you.
no problem, I'll be glad to help.

**Comment by CoooolRaoul** [comment] 2017-07-15 09:06
Since I'm at now, I've modified my schedule to have it run every 15 minutes
I don't understand why but it seem to be working (no more errors in the log)
I will collect the logs tomorrow to better pinpoint when it fails
Stay tuned

**Comment by CoooolRaoul** [comment] 2017-07-16 08:50
> Stay tuned

No connectivity errors since yesterday! (full log here: https://pastebin.com/e2skA93u)
I don't know why my Tasker 15mn schedule stopped working after midnight but that's another issue
I going to switch to built-in auto backup to see if it works again too.

**Comment by FelisPuma** [comment] 2017-07-16 08:56
I appreciate all the work @CoooolRaoul is doing tracking this down, but I'm pretty my issues is different. Notice that my manual backups are always successful, as are the INCOMING triggered ones for awhile, before they start getting the connectivity error. https://pastebin.com/v5FbEv3k Seems a lot like power management, but app is set to unmonitored.

**Comment by gpion** [comment] 2017-08-06 05:44
I don't think I've a different issue than yours @FelisPuma : like you, my manual backups are *always* successful. It's only ones automatically triggered in background which fails. 
I've modified my Tasker task to ping www.google.com and redirect output to sms_backup_plus.log just before triggering the backup:
```
Profile: SMS Backup (249)
	Time:  Every 6h
	State: Wifi Connected [ SSID:* MAC:* IP:* Active:Yes ]
Enter: SMS Backup (257)
	A1: Run Shell [ Command:ping -c1 www.google.com Timeout (Seconds):0 Use Root:Off Store Output In:%out Store Errors In: Store Result In: ] 
	A2: Write File [ File:sms_backup_plus.log Text:%out Append:On Add Newline:On ] 
	A3: Send Intent [ Action:com.zegoggles.smssync.BACKUP Cat:None Mime Type: Data: Extra: Extra: Extra: Package: Class: Target:Broadcast Receiver ] 

```
It appears that although ping is successful, log file show that backup fails with error.

Here's the log excerpt of a failed backup
```
PING www.google.com (74.125.206.105) 56(84) bytes of data.
64 bytes from wk-in-f105.1e100.net (74.125.206.105): icmp_seq=1 ttl=46 time=42.2 ms

--- www.google.com ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 42.244/42.244/42.244/0.000 ms
05-08 18:00 Sauvegarde demandée (application tierce)
05-08 18:00 Sauvegarde non effectuée, aucune connection
05-08 18:00 Sauvegarde effectuée
```

(_"Sauvegarde non effectuée, aucune connection"_ is the French for _"Backup skipped, no connectivity"_)

That's driving me crazy since it makes that app pretty much useless for me.

**Comment by jberkel** [comment] 2017-09-11 00:06
hmm, maybe it should just try to open the connection, regard less of what the system says

**Comment by rkleivel** [comment] 2017-10-07 11:12
Got the same problem on my new Galaxy Note8. It has worked flawlessly on my previous LG G5 on Android 7.0, and also on Galaxy S5 and Note3 before that.
Manual backup works every time, but automatic logs the following:

-10 07:35 Backup requested (regular)
06-10 07:35 Backup skipped, no connectivity
06-10 07:35 Backup finished
06-10 07:35 Next backup scheduled for: 13:35
06-10 08:44 Backup requested (regular)
06-10 08:44 Backup skipped, no connectivity
06-10 08:44 Backup finished
06-10 08:44 Next backup scheduled for: 14:44
06-10 19:31 Backup requested (incoming)
06-10 19:31 Backup skipped, no connectivity
06-10 19:31 Backup finished
06-10 19:31 Backup requested (incoming)
06-10 19:31 Backup skipped, no connectivity
06-10 19:31 Backup finished
06-10 21:07 Backup requested (incoming)
06-10 21:07 Backup skipped, no connectivity
06-10 21:07 Backup finished
06-10 21:10 Backup requested (incoming)
06-10 21:10 Backup skipped, no connectivity
06-10 21:10 Backup finished
07-10 11:17 Backup requested (incoming)
07-10 11:17 Backup skipped, no connectivity
07-10 11:17 Backup finished
07-10 13:01 Backup requested (manual)
07-10 13:01 Starting backup (MANUAL)
07-10 13:01 Backing up (32 SMS, 3 MMS, 13 call log)
07-10 13:02 Backup finished

**Comment by jcrben** [comment] 2018-03-31 16:52
@participants could any of you please try out the latest beta? https://github.com/jberkel/sms-backup-plus#beta

We want to know whether this is fixed before releasing 1.5.11.

**Comment by FelisPuma** [comment] 2018-04-04 20:30
I've installed the update, I'll let you know if there's a fix in a couple days. Thanks for looking into this issue!

**Comment by jcrben** [comment] 2018-04-14 15:54
@FelisPuma ping - would be good to get confirmation before releasing 1.5.11

**Comment by pcandme** [comment] 2018-04-18 01:06
Same issue here on Galaxy Note 8. I doubt this problem only happens on the Galaxy phones. Anyway, my phone's Android version is 8.0.0, the app version is 1.5.10, and the log is as follows:

```
(...many same errors...)
04-17 15:46 Backup requested (incoming)
04-17 15:46 Backup skipped, no connectivity
04-17 15:46 Backup finished
04-17 17:23 Backup requested (incoming)
04-17 17:23 Backup skipped, no connectivity
04-17 17:23 Backup finished
04-17 17:23 Backup requested (incoming)
04-17 17:23 Backup skipped, no connectivity
04-17 17:23 Backup finished
04-18 09:33 Backup requested (manual)
04-18 09:33 Starting backup (MANUAL)
04-18 09:33 Backing up (141 SMS, 18 MMS, 67 call log)
04-18 09:33 Backing up (141 SMS, 18 MMS, 67 call log)
04-18 09:39 Backup finished
```

As you can see, manual backup works well.

Thank you.

**Comment by pcandme** [comment] 2018-04-19 04:28
It started to work well since I did it manually yesterday. I changed the auto backup settings to 1 h for regular, 30 min for incoming schedule from shorter schedules, I'm not sure if this affects it.

**Comment by kurahaupo** [comment] 2021-07-08 22:45
Thanks everyone for the feedback.

Using the new Oreo JobScheduler API is on the roadmap.

I'm marking this as a duplicate of #758 just so we can track one issue and keep all the feedback in one place.

**Closed by kurahaupo** 2021-07-08 22:45 UTC
Labels: duplicate, schedule, v1.5.10
