### ISSUE TITLE
encoding error when restoring arabic messages.

### ISSUE THREAD

**Issue by samiemad** [jberkel/sms-backup-plus#533] opened 2015-02-01 17:32 UTC
I made a full backup of my messages a few days earlier, now when I try to restore them all I get is some '=', numbers and letters
eg: =D8 =D7 =86 =C7 ... etc

I guess the problem is somewhere in the encoding of text.

**Comment by jberkel** [comment] 2015-02-01 18:10
do you have a message i could use for testing ?

**Comment by samiemad** [comment] 2015-02-04 01:32
this message:
original message:
لديك 2  من باقة الرسائل المحلية صالحة لمدة 1 أيام.

restored message:
=D9=84=D8=AF=D9=8A=D9=83 2  =D9=85=D9=86 =D8=A8=D8=A7=D9=82=D8=A9 =D8=A7=D9=
=84=D8=B1=D8=B3=D8=A7=D8=A6=D9=84 =D8=A7=D9=84=D9=85=D8=AD=D9=84=D9=8A=D8=
=A9 =D8=B5=D8=A7=D9=84=D8=AD=D8=A9 =D9=84=D9=85=D8=AF=D8=A9 1 =D8=A3=D9=8A=
=D8=A7=D9=85=2E


I think I have seen the same pattern "=D2=E7...." in the past when I tried to send a note from an android phone to a nokia symbian6 phone

it appears that every arabic letter is replaced by 6 chars, eg: ل turns into "=D9=84"

**Comment by samiemad** [comment] 2015-02-04 01:39
I tried to fix the error myself, but I got a million errors when I imported to eclipse and was too lazy to debug them all :(

**Comment by jberkel** [comment] 2015-02-04 10:26
sorry, i can't reproduce. is this with the newest version ? and can you post the full headers of the email ?

**Comment by jberkel** [comment] 2015-02-04 10:28
also I'd recommend to use [Android Studio][] if you want to work on the code.

[Android Studio]: https://developer.android.com/sdk/index.html

**Comment by jberkel** [comment] 2015-03-03 12:19
closing this, insufficient information

**Closed by jberkel** 2015-03-03 12:19 UTC
