### ISSUE TITLE
"Sign-in Request" stuck in notification bar 

### ISSUE THREAD

**Issue by jimbo96** [jberkel/sms-backup-plus#612] opened 2015-11-15 12:36 UTC
I recently reset my Nexus 5 running Marshmallow, and now I have a constant item  in my notification bar from SMS Backup stating Sign-in Request", followed by my email address.  My texts are being backed up successfully to this gmail account, and I can find no way to remove this notification except by uninstalling the app. However, this notification reappears once I reinstall the app 

Thanks

**Comment by wnjuguna** [comment] 2015-12-02 22:47
I noted the same warning right after enabling 2 factor autentication on Gmail. Backups work though.

**Comment by sveltecode** [comment] 2016-02-03 15:33
Yup, getting this too.

**Comment by jberkel** [comment] 2016-02-04 00:24
And nothing happens when you tap the notification?

**Comment by wnjuguna** [comment] 2016-02-04 05:07
The warning disappeared eventually a while back. I've tried reproducing the issue by reinstalling smsbackup with no luck.

**Comment by jberkel** [comment] 2016-02-04 13:31
The notification is generated Android itself, but should only be displayed if a token cannot be obtained. Since the backup is still working this clearly not the case.

**Comment by wwwald** [comment] 2016-06-21 13:49
Same thing happening here. Enabled two-factor authentication, now the "Sign-in request" persist in the notification bar.

Tapping the notification shows a short message showing "Checking info", that quickly disappears, but the notification is still present afterwards.

SMS's _are_ backing up correctly, though.

**Comment by jberkel** [comment] 2016-06-22 14:54
@wwwald Do you remember the text on the notification? It's generated by the system, but it's possible that the app needs to do some sort of callback. It could also be an Android bug: 

https://productforums.google.com/forum/#!topic/play/KNHK5xQTZQs

Maybe just reboot the device as suggested in the link?

**Comment by wwwald** [comment] 2016-06-23 07:26
You are right: a reboot fixed it, the notification isn't there anymore. THANKS!

Just for the record, this was the notification:
<img src="https://cloud.githubusercontent.com/assets/39531/16294998/5a1cc786-3924-11e6-8ddd-cc214d61dc8d.png" width=400/>
Didn't manage to screenshot the "Checking info" popup as it disappears quickly.

**Comment by jberkel** [comment] 2018-03-28 19:33
looks like an Android bug (and now new reports since), closing

**Closed by jberkel** 2018-03-28 19:33 UTC
