### ISSUE TITLE
I get an, "unfortunately, SMS backup+ has stopped" popup several times a day 

### ISSUE THREAD

**Issue by graymoment** [jberkel/sms-backup-plus#659] opened 2016-07-06 02:48 UTC
I get these, "unfortunately, SMS backup+ has stopped" messages many times a day. I've clicked the "report" button and include the system log, but have never heard back. How do I fix it? 
I'm on a Galaxy Note 4 with Lollipop with all the latest updates.

**Comment by Nairou** [comment] 2016-08-23 15:24
I get the same thing now. Looking at the console in ADB, it appears that the app is running out of memory:

Throwing OutOfMemoryError "Failed to allocate a 142606346 byte allocation with 16765168 free bytes and 112MB until OOM"

Details:

`FATAL EXCEPTION: AsyncTask #2
 Process: com.zegoggles.smssync, PID: 30156
 java.lang.RuntimeException: An error occurred while executing doInBackground()
     at android.os.AsyncTask$3.done(AsyncTask.java:309)
     at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
     at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
     at java.util.concurrent.FutureTask.run(FutureTask.java:242)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
     at java.lang.Thread.run(Thread.java:818)
  Caused by: java.lang.OutOfMemoryError: Failed to allocate a 142606346 byte allocation with 16765168 free bytes and 112MB until OOM
     at java.io.ByteArrayOutputStream.expand(ByteArrayOutputStream.java:91)
     at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:216)
     at java.io.FilterOutputStream.write(FilterOutputStream.java:129)
     at com.fsck.k9.mail.filter.EOLConvertingOutputStream.write(EOLConvertingOutputStream.java:29)
     at java.io.FilterOutputStream.write(FilterOutputStream.java:114)
     at com.fsck.k9.mail.filter.Base64OutputStream.flush(Base64OutputStream.java:149)
     at com.fsck.k9.mail.filter.Base64OutputStream.write(Base64OutputStream.java:130)
     at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1793)
     at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1769)
     at org.apache.commons.io.IOUtils.copy(IOUtils.java:1744)
     at com.zegoggles.smssync.mail.Attachment$Base64Body.writeTo(Attachment.java:62)
     at com.fsck.k9.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:133)
     at com.fsck.k9.mail.internet.MimeMultipart.writeTo(MimeMultipart.java:94)
     at com.fsck.k9.mail.internet.MimeMessage.writeTo(MimeMessage.java:445)
     at com.fsck.k9.mail.store.imap.ImapStore$ImapFolder.appendMessages(ImapStore.java:1871)
     at com.zegoggles.smssync.mail.BackupImapStore$BackupFolder.appendMessages(BackupImapStore.java:230)
     at com.zegoggles.smssync.service.BackupTask.backupCursors(BackupTask.java:266)
     at com.zegoggles.smssync.service.BackupTask.fetchAndBackupItems(BackupTask.java:147)
     at com.zegoggles.smssync.service.BackupTask.acquireLocksAndBackup(BackupTask.java:127)
     at com.zegoggles.smssync.service.BackupTask.doInBackground(BackupTask.java:120)
     at com.zegoggles.smssync.service.BackupTask.doInBackground(BackupTask.java:47)
     at android.os.AsyncTask$2.call(AsyncTask.java:295)
     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
     at java.lang.Thread.run(Thread.java:818) `

**Comment by jockovonred** [comment] 2017-04-13 21:06
I was receiving a similar error via logcat:
```
FATAL EXCEPTION: AsyncTask #1
Process: com.zegoggles.smssync, PID: 13219
java.lang.RuntimeException: An error occured while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:300)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.OutOfMemoryError: Failed to allocate a 285212682 byte allocation with 16777216 free bytes and 92MB until OOM
	at java.io.ByteArrayOutputStream.expand(ByteArrayOutputStream.java:91)
	at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:216)
	at java.io.FilterOutputStream.write(FilterOutputStream.java:129)
	at com.fsck.k9.mail.filter.EOLConvertingOutputStream.write(EOLConvertingOutputStream.java:29)
	at java.io.FilterOutputStream.write(FilterOutputStream.java:114)
	at com.fsck.k9.mail.filter.Base64OutputStream.flush(Base64OutputStream.java:149)
	at com.fsck.k9.mail.filter.Base64OutputStream.write(Base64OutputStream.java:130)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1793)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1769)
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:1744)
	at com.zegoggles.smssync.mail.Attachment$Base64Body.writeTo(Attachment.java:62)
	at com.fsck.k9.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:133)
	at com.fsck.k9.mail.internet.MimeMultipart.writeTo(MimeMultipart.java:94)
	at com.fsck.k9.mail.internet.MimeMessage.writeTo(MimeMessage.java:445)
	at com.fsck.k9.mail.store.imap.ImapStore$ImapFolder.appendMessages(ImapStore.java:1871)
	at com.zegoggles.smssync.mail.BackupImapStore$BackupFolder.appendMessages(BackupImapStore.java:230)
	at com.zegoggles.smssync.service.BackupTask.backupCursors(BackupTask.java:266)
	at com.zegoggles.smssync.service.BackupTask.fetchAndBackupItems(BackupTask.java:147)
	at com.zegoggles.smssync.service.BackupTask.acquireLocksAndBackup(BackupTask.java:127)
	at com.zegoggles.smssync.service.BackupTask.doInBackground(BackupTask.java:120)
	at com.zegoggles.smssync.service.BackupTask.doInBackground(BackupTask.java:47)
	at android.os.AsyncTask$2.call(AsyncTask.java:288)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 3 more
```
The unfortunate effect was SMS Backup+ doesn't log this error other than an onscreen popup indicating "Unfortunately, SMS backup+ has stopped".  SMS messages however were being loaded to GMail, but MMS and Call Logs were NOT being uploaded.

Updating to 1.5.11-BETA3 seems to allow a number of MMS and Call Log records to be processed and uploaded.  The process is still running but it's doing more than it's done in a while without the error message popping up!

**Comment by jberkel** [comment] 2018-03-28 18:44
Closing this now since the issue seems to be fixed in the beta.

**Closed by jberkel** 2018-03-28 18:44 UTC
Labels: backup
