### ISSUE TITLE
Auto Backup Not Working

### ISSUE THREAD

**Issue by srewobwj** [jberkel/sms-backup-plus#779] opened 2017-08-12 16:29 UTC
Moto G4 | Android 7.0

"Auto backup" is checked but no longer works, automatically. Manual backups work fine.

Please advise.

TIA

**Comment by scottkolman** [comment] 2017-08-20 22:35
Same issue. It has been a long time now.

**Comment by scottkolman** [comment] 2017-08-20 22:38
Moto Z Force. Android 7.0. SMS Backup+ 1.5.10

**Comment by gpion** [comment] 2017-08-26 08:04
Already signaled here: 
https://github.com/jberkel/sms-backup-plus/issues/761

**Comment by srewobwj** [comment] 2017-08-28 17:32
Not sure it's the same issue. I don't get a "connectivity" warning after backups fail, because auto backups never start.

**Comment by gpion** [comment] 2017-08-28 17:46
> Not sure it's the same issue.
ok then, since there were so few information given (partial logs contents to start with) it was uneasy to make the difference.

**Comment by OmenLW** [comment] 2017-09-10 07:18
Same issue here as well. Manual backups work, auto backups do not.

LG V20

**Comment by jberkel** [comment] 2017-09-10 07:39
See #572

**Comment by PlainJane2017** [comment] 2017-09-14 16:35
I can't help but wondering if the Auto syncing issue started when Gmail disabled their XOAuth  to XOAuth2.  If I remember correctly, Gmail user should receive an email in 2015 notifying the user they will be changing their Authentication Method to XOAuth2 (wish I have that email). This is the time I believe the SMS Backup+  was having issue with the Auto syncing.  If you look on the SMS Backup+ app go to “Advanced settings” then “IMAP server settings the Authentication Method default for Gmail is “XOAuth”.  Should that be change to XOAuth2?  I could be wrong, but good or bad comment I would like to hear what your take on this.  I’ve used this app and thought this was a great app. Hopefully it can be fix.

**Comment by jberkel** [comment] 2017-09-17 10:06
@PlainJane2017 it could be that user tokens got invalidated, and that backup stopped working. in this case it should be enough to reconnect to the account.

the auth mechanism used is XOAuth2, i've just updated the UI strings to clarify

**Comment by mgollo** [comment] 2018-03-09 08:18
I am using an IMAP account with plaintext as Authentication method using STARTTLS for transport encryption and for me, the Auto Backup settings are completely unavailable (greyed out) on the latest version of SMSBackup+ from F-Droid on LineageOS 14.1. I had the app on my old phone (CopperheadOS based on Android 8.1) and as far as I remember, Automatic Backup did work there. I guess this is related to this issue.

**Comment by jberkel** [comment] 2018-03-09 09:05
@mgollo this has been fixed recently, the version on f-droid is not the most recent. you can download a version from the [releases](https://github.com/jberkel/sms-backup-plus/releases)

**Comment by jberkel** [comment] 2018-03-28 16:48
Closed as duplicate of several other issues

**Closed by jberkel** 2018-03-28 16:48 UTC
Labels: backup
