### ISSUE TITLE
SMS Backup+ Restore issue PLEASE help

### ISSUE THREAD

**Issue by amandanty2** [jberkel/sms-backup-plus#683] opened 2016-10-16 23:26 UTC
I have a Samsung Note 3 running 4.4.4   I tried to restore text from SMS Backup+ and almost none of the text were restored. They all show up as duplicates. Can someone please please help me? Most of the post I see are too old and the apps needed are no longer available for download.

**Comment by Woi** [comment] 2018-02-23 16:13
duplicate of #684

**Closed** 2018-03-28 20:11 UTC
