### ISSUE TITLE
SMS Restore NOT working.

### ISSUE THREAD

**Issue by nafeasonto** [jberkel/sms-backup-plus#738] opened 2017-03-27 16:56 UTC
This is VERY imporant that I restore these texts messages from GMAIL.  It could mean by livelyhood.  The restore keeps giving an I/O error, the Backup works fine.

I am running your latest release on this page.

I am useing a Galaxy S6 with XtroLite Firmware.  Also XPOSED.  Is something interfering?  Is an an adblocker?  What oculd be causing this?

**Comment by parker5635** [comment] 2017-05-30 15:13
[675](https://github.com/jberkel/sms-backup-plus/issues/675)

**Comment by LittleTimmyHartwell** [comment] 2017-12-10 01:14
There is No Support for this App.

**Comment by jberkel** [comment] 2017-12-19 21:38
Duplicate of #675

**Closed by jberkel** 2017-12-19 21:38 UTC
