### ISSUE TITLE
Can't log into Google account on new phone 

### ISSUE THREAD

**Issue by turkeyphant** [jberkel/sms-backup-plus#1035] opened 2020-09-25 16:41 UTC
Before you report your issue, please consider perusing the [https://github.com/jberkel/sms-backup-plus#faq](FAQ) and searching the issues page to see if it has already been reported.

### Expected behaviour
Tap to connect connects to Google account

### Actual behaviour
![2020-09-25 17 39 41](https://user-images.githubusercontent.com/8129583/94293419-21596b00-ff56-11ea-9125-34fc01d81764.jpg)

![2020-09-23 17 52 35](https://user-images.githubusercontent.com/8129583/94293373-11da2200-ff56-11ea-834b-f78f00613e77.jpg)

### Steps to reproduce the behaviour
Tap to connect
Tap Google account
Tap OK

### Please specify the following:

* Android version 10
* Phone model / brand SM-G970F
* SMS Backup+ version installed 1.5.11
* Messaging app Messages

**Comment by kurahaupo** [comment] 2020-10-02 08:02
Thankyou for the details, but this is a duplicate of existing bug #970.

May I ask, how did you get to the "submit a bug" form?

(I ask because as far as I knew, the only way to get there was via the main app page, which starts with an emphatic note about exactly this issue.)

Also, how can we make it clearer in the bug template that it's necessary to read the FAQ and the existing bugs list before submitting a "new" bug, as most bugs are in fact already known about?

To solve your issue, please now read the first paragraph of the important [note on the main app page](https://github.com/jberkel/sms-backup-plus#note), and the introductory sections of bug reports #959, #970, and #972.

**Comment by turkeyphant** [comment] 2020-10-02 14:05
Apologies. There was no contact information in the app and I just googled "sms backup plus issues". Is it not possible to just add a message in the app to notify the user?

**Closed** 2020-10-02 14:05 UTC
Labels: xoauth
