### ISSUE TITLE
Wont woork 

### ISSUE THREAD

**Issue by mhertweck** [jberkel/sms-backup-plus#997] opened 2019-12-13 07:18 UTC
WILL IT NOT WORK WITH GOOGLE ANYMORE SO I HAD IT SET WITH IIMP WITH OUTLOOK USING STARLITES AND I FACTORY RESET MY SYYLO 4 PHONE AND NOW I CANT REMEMBER HOW TO DO THIS AGAIN STTP WAY WITH OUTLOOK EMAIL

**Comment by kurahaupo** [comment] 2019-12-19 14:29
I understand that you're frustrated, but if you just want help connecting SMS Backup+ to your account, it would be helpful to just ask for that. Omit most of the history, and to acknowledge that you've ignored these questions:

<blockquote>

Before you report your issue, please consider perusing the [FAQ](https://github.com/jberkel/sms-backup-plus#faq) and searching the issues page to see if it has already been reported.

### Expected behaviour
### Actual behaviour
### Steps to reproduce the behaviour
### Please specify the following:
* Android version
* Phone model / brand
* SMS Backup+ version installed
* Messaging app
</blockquote>

Please take more care with spelling, as I have no idea what you mean by "STTP WAY". Nor is it clear whether you mean "Outlook" the email client, or "Outlook" the service provided by Microsoft.

Taking a wild stab at what you actually meant, if you want to know the IMAP settings for Outlook.com please read [the documentation provided by Microsoft](https://support.office.com/en-us/article/POP-IMAP-and-SMTP-settings-for-Outlook-com-d088b986-291d-42b8-9564-9c414e2aa040). And if you mean that you stopped using Gmail.com and switched to Outlook.com because of the requirement to use IMAP, that wasn't actually necessary as Gmail also supports IMAP.

**Comment by kurahaupo** [comment] 2020-07-15 12:02
If you're still reading this, read the instructions on issue #970.
closing.

**Closed by kurahaupo** 2020-07-15 12:02 UTC
Labels: awaiting response, bespoke
