### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by mcelligott56** [jberkel/sms-backup-plus#1071] opened 2021-09-07 19:08 UTC
Before you report your issue, please consider perusing the [FAQ](https://github.com/jberkel/sms-backup-plus#faq) and searching the issues page to see if it has already been reported.

### Actual behaviour

When I try to back up my messages, I get an error saying unable to connect. 

### Please specify the following:

* Android version
  My android version is 11
* Phone model / brand
  I have the Samsung galaxy s20 plus
* SMS Backup+ version installed
  The app version is 1.5.11
* Messaging app
  I use messages to send SMS and MMS.

![Screenshot_20210907-150054_SMS Backup+](https://user-images.githubusercontent.com/3492700/132398013-68b0cee4-26f7-4fed-86a7-0685544ab783.jpg)
![Screenshot_20210907-150054_SMS Backup+](https://user-images.githubusercontent.com/3492700/132398031-4aa3d3b3-8ff0-470f-9dea-e698ee9a168b.jpg)
![Screenshot_20210907-150102_SMS Backup+](https://user-images.githubusercontent.com/3492700/132398037-30637e1e-7ae3-4ca2-afac-65d888417444.jpg)

**Comment by kurahaupo** [comment] 2021-09-28 07:30
> Unable to resolve host "imap.google.com": No address associated with hostname

It appears that Google have discontinued that name. (Geeze, thanks for letting us know...)

Change it to `imap.gmail.com` instead.

**Comment by JerryTg** [comment] 2021-12-29 22:02
Is the APP still working with google email?
I have tried to backup my SMS/MMS, with various settings mentioned here, with no success.

Android version: 10
Samsung Galaxy Note 9
The app version is 1.5.11
Using Messages 
When I try to connect, 

"This app is blocked
This app tried to access sensitive info in your google Account. To keep your account safe, Google blocked access"

I used the updated IMAP address:
imap.gmail.com:993
used the google generated 16-digit app password

**Comment by kurahaupo** [comment] 2021-12-30 00:35
@JerryTg yes it still works for me.

When did you first install the app?

**Comment by kurahaupo** [comment] 2021-12-30 00:42
@JerryTg your issue appears to be a duplicate of #1046.

**Closed by kurahaupo** 2021-12-30 00:42 UTC

**Comment by mcelligott56** [comment] 2021-12-30 01:14
Go into custom imap server and under username, enter your Gmail address.
You will need to make an app password and enter that in the password field.
Follow the instructions in the following link to make an app password -
https://support.google.com/accounts/answer/185833?hl=en. Hope that helps.

Denis McElligott

**Comment by kurahaupo** [comment] 2021-12-30 05:05
@mcelligott56 Did changing the imap hostname resolve this issue?

**Comment by JerryTg** [comment] 2021-12-30 05:40
Ok, it's working now.
I think the problem last time was I changed the authentication back out of
the "Plain Text" after I input the password.
Somehow that probably erased the password I input, hence the error message.
I need to keep the authentication as plain text after input the password.
Thank you very much for the help.

Jerry

**Comment by mcelligott56** [comment] 2021-12-30 10:19
All I did was put my Gmail account in the username field and generate an
app password for the password field. I left the server field blank.

Denis McElligott
