### ISSUE TITLE
Call log backing up, but not MMS nor SMS [sent via Signal]

### ISSUE THREAD

**Issue by avicado** [jberkel/sms-backup-plus#817] opened 2017-10-17 16:28 UTC
First of all, I just want to say I really love your app - thank you!
Every so often I get notification error messages, like "IO error" or some kind of authentication error. I'll investigate and find that not everything has been automatically backed up. I'll perform a manual backup, only to find that the call logs get backed up but nothing else does.
I do have 2 Factor authentication turned on my Google account - does that get in the way? Do I need to create a separate app password for SMS Backup+
Everything was working fine on my Samsung Galaxy S4... but then it stopped consistently working when I transferred over to a Samsung Galaxy J7 Perx. Now that I'm on an LG stylus, it appears to be working better, yet still hasn't backed up any MMS messages since February 2017.
Thanks in advance for your assistance and advice!

**Comment by Bobbi1970** [comment] 2018-01-24 21:29
I'm having the same problem. Have you found a solution as of yet?

**Comment by avicado** [comment] 2018-02-19 12:03
I have not. I'm extremely disappointed.
I just tried setting SMS Backup+ as my default messaging app, using the reset option within the app, and attempting to synchronize again... it appeared to get to about 15 SMS messages before stalling.
The log appeared to indicate that the auto backup tried to start during this manual backup - perhaps that caused both to fail?
I'm usually pretty good at troubleshooting technical issues, but I'm not going to fumble blindly in the dark with a product that hasn't been updated in 2.5 years (and that the author himself doesn't deign to check his own github on a regular basis). Libraries and protocols can change over time, and if a programmer is going to abandon his own product, the least he could do is recommend a decent replacement.

**Comment by avicado** [comment] 2018-02-19 12:13
My apologies for the tone of my last comment - having looked through the closed issues, I see that Jan does visit this github more often than I had surmised. I am sorry for making an incorrect assumption without checking first.
I also realized that I neglected to mention that my default SMS application is Signal. I don't understand why it was working before and no longer works, however, unless a recent update in Signal cut off access to the local SMS store.

**Comment by jberkel** [comment] 2018-02-21 16:45
@avicado for signal, see #841. also please try the beta version, it gets updated frequently. I will release a new "official" version soon.

**Comment by avicado** [comment] 2018-02-21 17:24
Awesome - thank you so much for the tip & the speedy response! 👍

**Comment by avicado** [comment] 2018-02-21 17:27
Sorry, could you please clarify - you did mean try the beta version of SMS Backup+, not the beta version of Signal, correct?
I'm assuming I can find the APK here on GitHub?
Thank you in advance!

**Comment by jberkel** [comment] 2018-02-21 20:04
@avicado yes, you can find the latest APK here: [1.5.11-BETA12](https://github.com/jberkel/sms-backup-plus/releases/tag/1.5.11-BETA12)

**Comment by jberkel** [comment] 2018-03-04 23:23
@Androidsimon see https://github.com/jberkel/sms-backup-plus#beta

**Comment by jberkel** [comment] 2018-03-28 16:41
Closing as duplicate of #841

**Closed by jberkel** 2018-03-28 16:41 UTC
