### ISSUE TITLE
Not restoring completely using Android 5.0.2 on Samsung Galaxy S3

### ISSUE THREAD

**Issue by nesak83** [jberkel/sms-backup-plus#541] opened 2015-03-14 10:00 UTC
I have 8000 plus message to restore but however it didnt restore completely. Only few hundreds of old old sms were restored.   After it completed restored, it showing "updating threads" on the notification bar.  

Then after finishing restoring all ~8000 messages without error, SMS Backup+ reports that all my SMS were duplicates.

I checked in privary guard setting and read sms/mms was turned on for  SMS Backup+ setting.

I downloaded the beta version 1.59 beta 3 and it still the same.. Pls help

**Comment by romainneutron** [comment] 2015-05-07 08:56
Got the same issue

**Comment by romainneutron** [comment] 2015-05-07 08:58
Seems duplicate of #527

**Comment by jberkel** [comment] 2018-03-28 20:03
Dup

**Closed by jberkel** 2018-03-28 20:03 UTC
Labels: restore
