### ISSUE TITLE
Cannot Restore Messages Due to IO Error

### ISSUE THREAD

**Issue by chanranks** [jberkel/sms-backup-plus#756] opened 2017-05-02 18:30 UTC
I just switched phones and am attempting to restore message on Samsung S6, running stock Marshmallow (6.0.1). with no luck and an error.

- SMSB+ set as default messaging app
- Backup stored on Gmail account
- After pressing Restore, shows "Working" and "Calculating..."
- After about 30-40 seconds, shows "Error" and "Error during backup/restore: IO Error"
- Pop notification appears "Change messaging app?; Do you want to use Messages instead of SMSB+ as your default messaging app?"
- I varied the number of messages to retrieve resulting in the same error.

I've reviewed previous threads and didn't see any solutions on this specific issue. If I missed it please redirect (and forgive) me. Any help would be appreciated.

**Comment by parker5635** [comment] 2017-05-30 15:13
[675](https://github.com/jberkel/sms-backup-plus/issues/675)

**Comment by idealcalvin** [comment] 2017-06-13 05:26
I am having the same issue, I did a factory reset and now its shows IO Error when I go to restore, please advice.

**Comment by jberkel** [comment] 2017-12-19 21:37
Duplicate of #675

**Closed by jberkel** 2017-12-19 21:37 UTC
