### ISSUE TITLE
Outgoing Texts [Advanced Messaging] Stopped Being BackedUp

### ISSUE THREAD

**Issue by littlebit0628** [jberkel/sms-backup-plus#715] opened 2017-02-15 02:31 UTC
Hi - I have a Samsung Galaxy S6 with the newest software update. I have been backing up my text messages at the end of each month with this program for close to 2 years now. I went back to find a conversation in November I had for my job and realized that my outgoing texts are no longer being backed up. I have tried to uninstall and reinstall the program, yet it still seems to only backing up my received messages. Anyone else have any problems like this? Any solutions for what I can do?

**Comment by ferdilverdil** [comment] 2017-02-15 16:19
Same phone. Same problem. Tried the same solution (uninstalling and reinstalling the app). No luck.  Things were working fine for awhile then sent messsages stopped being backed-up .  I notified Jberkel over a year ago when my outgoing messages stopped backing up in January 2016. Never got a reply. Never resolved the problem.

**Comment by Architek01** [comment] 2017-02-21 17:04
It has to do with the "advanced messaging" setting. I had to turn mine off, but I'm still trying to figure out how to back up 4 months worth of text without screen spotting it all. I hope all fixed cone soon!

**Comment by steeleranch** [comment] 2017-04-25 12:02
Same issue here - Samsung S7 Edge - outgoing text not being backed up. VERY FRUSTRATING! I emailed and checked online forums for fix and can't find one.

**Comment by Architek01** [comment] 2017-04-25 12:04
I had to turn off the advanced messages feature in settings.

**Comment by steeleranch** [comment] 2017-04-26 13:59
Advanced settings is not on - there is nothing selected and still doesn't capture outgoing SMS

**Comment by vman465** [comment] 2017-05-01 04:02
Same here also. Have the new Galaxy S8 and Notice this issue as well. I tried everything under the sun. Can't figure it out. If anyone finds a fix, please me know. Very frustrating!

**Comment by Zurnic** [comment] 2017-11-13 15:30
I can confirm that turning off Advanced Messaging in the settings of the Message app fixes this issue. Doesn't fix any old texts that have been sent however. Would prefer this be addressed because Advanced Messaging is very useful.

**Comment by Woi** [comment] 2018-02-23 16:17
See https://github.com/jberkel/sms-backup-plus/issues/665#issuecomment-368053785

**Comment by jberkel** [comment] 2018-03-28 18:36
Sorry won't be addressed, closing

**Closed by jberkel** 2018-03-28 18:36 UTC
Labels: backup
