### ISSUE TITLE
SMS Backup + is not Automatically backing up. Settings appear correct and manual works

### ISSUE THREAD

**Issue by FanOfNoMan** [jberkel/sms-backup-plus#1058] opened 2021-04-04 19:37 UTC
Before you report your issue, please consider perusing the [FAQ](https://github.com/jberkel/sms-backup-plus#faq) and searching the issues page to see if it has already been reported.

### Expected behaviour 

(edited) Backups should occur automatically

### Actual behaviour

(edited) SMS Backup + is not automatically backing up.

### Steps to reproduce the behaviour

(edited) Settings appear correct and manual works

### Device details

* Android version 11
* Phone model / brand Galaxy A71 5G
* SMS Backup+ version installed 1.5.11
* Messaging app Messages

**Comment by JenBcute** [comment] 2021-05-25 21:26
Is this not automatically backing up anymore only because I have Android 11?
Is there any work around to fix this?

**Comment by kurahaupo** [comment] 2021-06-11 17:52
Likely duplicate of #954

**Closed by kurahaupo** 2021-06-11 17:52 UTC
Labels: schedule

**Comment by kurahaupo** [comment] 2021-07-08 22:47
Thanks everyone for the feedback.

Using the new Oreo JobScheduler API is on the roadmap.

I'm marking this as a duplicate of #758 just so we can track one issue and keep all the feedback in one place.
